# Ei-parametriset testit {#sec-ei-parametriset-testit}

**Ei-parametriset testit** ovat testiperhe, jolla on vähemmän odotuksia datan jakaumalta ja vähemmän mallioletuksia kuin parametrisilla lineaarisilla testeillä. Näitä testejä voi käyttää useimmissa tapauksissa, joissa lineaarisen testin oletukset eivät täyty, esimerkiksi jos otoskoko on pieni.

Yhteiskunta- ja ihmistieteissä **muut robustit mitat**, esimerkiksi **bootstrap**-mitat, ovat pitkälti korvanneet ei-parametriset testit. Näitä on kuitenkin vaikea tehdä Excelissä, ja ei-parametrisiä testejä käytetään myös yleisesti luonnontieteissä, joten niiden osaaminen on tärkeää.

Perusajatuksena ei-parametrisissa testeissä on, että data ensin **järjestetään**, jolloin merkitsevyys- sekä erotestit tuotetaan järjestysnumeroiden pohjalta. Tämä korjaa esimerkiksi ääripääarvojen ja vinouman vääristymiä.[^eiparametrisettestit-1]

[^eiparametrisettestit-1]: Kahdeskymmenes datapiste on aina kahdeskymmenes datapiste, olkoon kuinka iso tahansa verrattuna muihin datapisteisiin!

Ei-parametriset testit voivat kuulostaa loistavalta vaihtoehdolta: ne testaavat merkitsevyyttä, mutta ne eivät vaadi suuria otoskokoja tai useampien mallioletusten täyttymistä! [Negatiivisena puolena ei-parametrisillä testeillä on yleensä matalampi **tilastollinen voima** (engl. *statistical power*).]{.underline} Tilastollisella voimalla tarkoitetaan testin kykyä tunnistaa **todelliset positiiviset**, eli hylätä nollahypoteesi tilanteessa, jossa sen pitikin hylätä. Matalan voiman testeillä todellisia positiivisia tunnistetaan heikommin, jolloin tulee useammin vastaan tilanteita, joissa et pysty hylkäämään nollahypoteesia vaikka sen hylkääminen todellisuudessa olisi oikein.

Tämän takia nyrkkisääntönä onkin, että [käytät parametrisia lineaarisia malleja jos ja kun mallioletukset täyttyvät]{.underline}, ja ei-parametrisia testejä vain jos mallioletukset eivät täyty.

Tässä kirjassa käydään läpi neljä ei-parametristä testiä:

1.  **Merkkitesti** (vastaa yhden otoksen t-testiä)
2.  **Wilcoxonin signed-rank** -testi (vastaa parittaisen otoksen t-testiä)
3.  **Mann-Whitney'n U-testi** (vastaa kahden otoksen t-testiä)
4.  **Spearmanin rho** (vastaa Pearsonin korrelaatiokertointa)

## Merkkitesti {#sec-merkkitesti-teoria}

**Mittausasteikot**: Järjestysasteikosta ylöspäin

**Merkkitesti** on yksimuuttujatesti, eli vastaa parametristä **yhden otoksen t-testiä** (ks. @sec-yhden-otoksen-t-testi-teoria). Merkkitestillä testataan, onko otoksen mediaani merkitsevästi eri kuin nollahypoteesin olettama mediaani. T-testissä käytetään keskiarvoa, merkkitestissä käytetään mediaania. Molemmissa testeissä määritellään myös arvo, jota vastaan testataan, eli nollahypoteesina arvo.

[Merkkitestin voi toteuttaa **yksi-** tai **kaksihäntäisenä**]{.underline}. Tämän tunnistaa helpoiten nolla- ja vaihtoehtohypoteesin muotoilusta:

> Jos vaihtoehtohypoteesisi ehdottaa vain eroa ("populaatiomediaani [ei ole]{.underline} yhtä kuin X"), merkkitesti tulee toteuttaa **kaksihäntäisenä**.
>
> Jos vaihtoehtohypoteesisi ehdottaa suuntaa ja eroa ("populaatiomediaani on suurempi/pienempi kuin X"), merkkitesti tulee toteuttaa **yksihäntäisenä**.

[Merkkitestin voi myös tehdä kahden muuttujan välillä]{.underline}, jolloin tarkastetaan erojen mediaani. Tällöin testi voi olla **parittainen** merkkitesti. Tämä on suoraan verrattavissa **parittaiseen t-testiin**. Huomioi, että merkkitestiä ei voi tehdä kahden otoksen ei-paritetulle muuttujaparille (eli tilanteessa, jossa muuttujat edustavat eri ryhmiä). Tällöin on käytettävä jotain muuta testiä, esim. Mann-Whitney'n U-testiä (ks. @sec-mann-whitneyn-u-testi).

[Merkkitestin ideana]{.underline} on, että tutkija määrittelee jokaiselle arvolle **merkin** $+$, $-$ tai $0$. Nämä osoittavat, onko arvo yli, ali vai sama kuin nollahypoteesin ehdottama arvo $k$. Jos esimerkiksi nollahypoteesi ehdottaa, että populaation mediaani on $5$, niin merkataan kaikki arvot yli viiden plus-merkillä, kaikki alle viiden minus-merkillä, ja kaikki viiden arvot nollalla.

[Merkkauksen jälkeen kaikki plussat, minukset ja nollat lasketaan]{.underline}. Sitten käytetään **binomijakaumaa** hakeaksemme, kuinka todennäköistä oli saada niin monta plussaa/minusta kuin datamme näyttää, jos nollahypoteesi on tosi (ja plussien/minusten määrä tulisi olla sama ja siten mediaanin ympäröimä).

### Mallioletukset {#sec-merkkitesti-mallioletukset}

Vaikka merkkitesti on ei-parametrinen testi, sillä on kuitenkin joitain mallioletuksia.

[Kaikki merkkitestivariantit olettavat, että muuttuja(t) on/ovat **satunnaisesti otettuja populaatiosta**]{.underline}. Jos näin ei ole, testin jakaumaoletus ei välttämättä mallinna todellista suhdetta luotettavasti. Tämä oletus pätee käytännössä kaikkiin frekvenssitilastotieteen malleihin, joten sitä ei edes usein ilmaista oletuksena.

[Parittainen merkkitesti olettaa, että muuttujat voidaan **parittaa riveittäin**]{.underline}. Toisin sanoen, muuttujien pitää olla riippuvaisia toisistaan. Jokaiselle yksikölle tulee löytyä arvo molemmilla muuttujilla.

### Merkkitestin toteuttaminen Excelissä {#sec-merkkitestin-toteuttaminen-excelissä}

Merkkitesti toteutetaan Excelissä omilla laskuilla, koska laskukaavaa ei ole. Toteuttaminen käy vaiheissa:

1.  Määrittele nollahypoteesin mediaaniraja (esim. $\text{Md} = 5$).
2.  Määrittele vaihtoehtohypoteesin suunta (suurempi, pienempi vai eri).
    1.  Jos vain eri kuin nollahypoteesi, laske kaksihäntäinen merkkitesti.
    2.  Jos suurempi tai pienempi, laske yksihäntäinen merkkitesti.
3.  Määrittele jokaiselle datapisteelle merkki `JOS`-funktiolla: `=JOS(solu > nollaraja; 1; JOS(solu = nollaraja; 0; -1))`
4.  Laske positiivisten ja negatiivisten merkkien määrät: `=LASKE.JOS(alue; -1)` ja `=LASKE.JOS(alue; 1)`
5.  Laske vaihtoehtohypoteesia edustava otoskoko summaamalla positiivisten ja negatiivisten merkkien määrät yhteen.
6.  Laske p-arvo:
    1.  Kaksihäntäinen merkkitesti: `=BINOMI.JAKAUMA(pienin_merkkimäärä; otoskoko; 0,5; TOSI) * 2`
    2.  Yksihäntäinen merkkitesti: `=BINOMI.JAKAUMA(merkkimäärä; otoskoko; 0,5; TOSI)`

[P-arvon laskukaavio riippuu häntäisyydestä]{.underline}. **Kaksihäntäisessä testissä** käytetään joko negatiivisten tai positiivisten merkkien määrää, riippuen siitä, kumpi on pienempi. Koska testissä käytetään molempia häntiä, todennäköisyys kerrotaan kahdella. **Yksihäntäisessä testissä** käytetään sitä merkkimäärää, jota halutaan testata (positiiviset jos vaihtoehtohypoteesi ehdottaa suurempaa, negatiiviset jos pienempää), ja p-arvo raportoidaan sellaisenaan.

### Merkkitestin raportointi {#sec-merkkitestin-raportointi}

Merkkitestin testisuureena käytetään sitä merkkimäärää, jolla laskettiin p-arvo. Testille tulee mieluisesti raportoida seuraavat:

-   Testattava mediaani $\text{Md}$

-   Nollahypoteesin raja-arvo

-   Testin häntäisyys sekä suunta (jos yksihäntäinen)

    -   Jos kaksihäntäinen: Kumpi merkkimääristä testattiin

-   Testin suure (merkkimäärä, jota testattiin)

-   Otoskoko

-   P-arvo

[Toisin sanottuna, raportoi käytännössä kaikki arvot]{.underline}, jotka laskit.

## Wilcoxonin signed-rank-testi {#sec-wilcoxonin-signed-rank-testi-teoria}

**Mittausasteikot:** Välimatka- ja suhdeasteikko.

**Wilcoxonin signed-rank-testi** (myös Wilcoxonin rankitesti parivertailulle[^eiparametrisettestit-2], tai vain Wilcoxonin testi[^eiparametrisettestit-3]) on ei-parametrinen vastine **parittaisen otoksen t-testille** (ks. @sec-parittaisen-otoksen-t-testi-teoria). Testillä testataan, eroavatko kaksi muuttujaa toisistaan merkitsevästi.

[^eiparametrisettestit-2]: Tämä on mielestäni niin hirvittävä käännösnimi, että en suostu sitä käyttämään.

[^eiparametrisettestit-3]: Wilcoxonin testi voi joskus myös viitata **Wilcoxonin rankisummatestiin** (engl. *Wilcoxon rank-sum test*), joka on käytännössä sama kuin Mann-Whitney'n U-testi. Tilastotiede on usein tällä tavalla sekavasti nimetty. Yleisesti ottaen kuitenkin Wilcoxonin testillä viitataan tähän parittaisten muuttujien testiin. Tutkimusasetelmasta voit myös päätellä, onko kyseessä parittainen testi vai kahden otoksen testi.

Testi on jokseenkin samanlainen kuin merkkitesti, mutta kahdella tärkeällä erolla. Ensinnäkin testille lasketaan kahden muuttujan parien **erot**, ja toiseksi nämä **asetetaan järjestykseen** ennen testaamista.

Myös Wilcoxonin testin voi tehdä **yksi-** tai **kaksihäntäisenä**. Häntäisyysvalinta vaikuttaa merkitsevyyden laskemiseen.

### Mallioletukset {#sec-wilcoxonin-signed-rank-mallioletukset}

Kuten merkkitesti, Wilcoxonin testi ei oleta paljoa.

[Mittausasteikon tulisi olla välimatka- tai suhdeasteikko]{.underline} (koska laskemme eroja muuttujien välillä).

Testi olettaa myös, että [mittaukset ovat paritettuja]{.underline}; jos mittauksesi on kahden otoksen ei-paritettu otanta, käytä Mann-Whitney'n U-testiä (ks. @sec-mann-whitneyn-u-testi).

Kuten kaikissa ei-parametrisissa testeissä: jos täytät lineaarisen mallin vaatimukset, käytä sitä ei-parametrisen testin sijaan.

### Wilcoxonin testin laskeminen {#sec-wilcoxonin-testin-laskeminen}

[Testin logiikka on suoraviivainen]{.underline}:

1.  Laske muuttujien väliset erot.
2.  Merkitse niiden merkit (positiivinen vai negatiivinen; jätä pois nollat)
3.  Aseta erot suuruusjärjestykseen absoluuttisen arvon (itseisarvon) mukaan. Älä siis ota huomioon merkkiä tässä vaiheessa.
4.  Summaa järjestysnumerot erikseen positiivisille ja negatiivisille arvoille.
5.  Laske testin keskiarvo, keskihajonta ja z-arvot.
6.  Vertaa z-arvoja kriittisiin arvoihin ja hae p-arvo.

[Muuttujien väliset erot lasketaan yksinkertaisesti]{.underline} $x_i - y_i$, jossa $i$ on rivin numero. Laske siis erot muuttujien välillä jokaiselle riville.

[Näistä eroista jätetään pois kaikki nollat]{.underline}, eli ne voivat jäädä pois seuraavista laskuista kokonaan.

[Aseta seuraavaksi positiiviset ja negatiiviset erot järjestyksiin]{.underline}; anna järjestysnumero $1$ pienimmälle, $2$ seuraavaksi isommalle, jne., kunnes kaikki ei-nollat arvot ovat järjestettyjä.

[Jos kaksi tai useampi arvo saisi saman järjestysnumeron]{.underline}, anna niille ensin nousevat järjestysnumerot, ja laske sitten niiden keskiarvo. Kaikki samat arvot saavat silloin saman keskiarvojärjestysnumeron. Jatka sitten numerointia siitä kohtaa, mihin se olisi jäänyt, jos arvot eivät olisi samansuuruisia.

Jos arvot esimerkiksi ovat $\{3, 4, 5, 5, 6\}$, niiden järjestysarvot olisivat $\{1, 2, (3), (4), 5\}$. Koska kaksi arvoa kuitenkin ovat samankokoisia, lasketaan niiden mahdollisten järjestysarvojen keskiarvo ja määritetään se järjestysnumeroksi: $(3+4)/2 = 7/2 = 3.5$. Täten saadaan lopulliset järjestysnumerot $\{1, 2, 3.5, 3.5, 5\}$. Huomaa, että viimeinen arvo sai järjestysnumeron, jonka se olisi saanut jos samanlaisia arvoja ei olisi ollut alkuperäisessä järjestyksessä.

[Summaa sitten järjestysnumerot yhteen kahdelle merkille erikseen]{.underline}: $T = \sum_{i=1}^n{J_i}$ , jossa $J_i$ on arvon $i$ järjestysnumero. $n$ on tässä tilanteessa positiivisten tai negatiivisten arvojen määrä, ilman nolla-arvoja.

[Tässä vaiheessa voimme jo hakea merkitsevyyden kriittisten arvojen taulukosta]{.underline}. Merkitsevyys pohjautuu otoskokoon ja alfa-arvoon.

[Jos kuitenkin otoskoko on yli noin 25]{.underline}, voimme myös käyttää **z-normalisointia** hakeaksemme tarkan (ja hieman voimakkaamman) p-arvon.

[Tällöin lasketaan testin keskiarvo ja keskihajonta]{.underline}, jotka molemmat pohjautuvat testikokoon:

$$
\begin{split}
\bar{T} = \frac{n(n+1)}{4}
\\ \text{SE}_{\bar{T}} = \sqrt{\frac{n(n+1)(2n+1)}{24}}
\end{split}
$$ {#eq-wilcoxonin-testi-keskiarvo-ja-keskihajonta}

**Keskiarvo** lasketaan kertomalla otoskoko itsellään plus yksi, ja jakamalla tulos neljällä.

**Keskihajonta** saadaan ensin kertomalla otoskoko, otoskoko plus yksi, sekä kaksi kertaa otoskoko plus yksi yhteen, jakamalla tulos 24:llä, ja ottamalla tämän tuloksen neliöjuuri.

**Otoskokoina käytetään ryhmän kokoa ilman nolla-arvoja.** Jos sinulla oli esimerkiksi kymmenen riviä, joista kaksi saivat erotuksessa nolla-arvon, otoskoko testille on kahdeksan.

[Viimeiseksi lasketaan z-arvot.]{.underline} Koska z-arvon yleiskaava on $z = \frac{X-\bar{X}}{s}$, voimme vain korvata symbolit laskemillamme arvoilla:\

$$
z_T = \frac{T-\bar{T}}{SE_{\bar{T}}}
$$ {#eq-wilcoxonin-testi-z-normalisointi}

Voimme sitten hakea z-arvon merkitsevyyden kriittisten arvojen taulukolla tai laskurilla.

### Wilcoxonin testin toteuttaminen Excelissä {#sec-wilcoxonin-testin-toteuttaminen-excelissä}

[Kuten merkkitesti, Wilcoxonin testi toteutetaan käsin Excelissä]{.underline}:

1.  Valitse muuttujat, joita haluat verrata.
2.  Laske muuttujien välinen ero: `=muuttuja1 - muuttuja2`
    1.  Jos käytät muuttujanimiä suoraan, voit saada dynaamisen matriisin. Muuten joudut syöttämään kaavan soluihin yksitellen vetotoiminnolla.
3.  Määrittele jokaiselle erolle suuntamerkki: `=JOS(solu > nollaraja; 1; JOS(solu = nollaraja; 0; -1))`
    1.  Tämä on sama kaavio kuin merkkitestille.
4.  Laske absoluuttiset erot: `=ITSEISARVO(solu)`
5.  Järjestä absoluuttiset arvot: `=JOS(solu = 0; ""; ARVON.MUKAAN.KESKIARVO(järjestettävä_arvo; järjestysalue; 1))`
    1.  Funktio kopioidaan kaikille riveille erikseen. Lukitse järjestysalue jotta vetotoiminto tai kopiointi ei siirrä tätä aluetta.
6.  Tee uudet sarakkeet, jonne merkitset positiivisten ja negatiivisten arvojen järjestysarvot erikseen.
    1.  Positiiviset arvot: `=JOS(alkuperäinen_arvo > 0; absoluuttinen_järjestys; "")`
    2.  Negatiiviset arvot: `=JOS(alkuperäinen_arvo < 0; absoluuttinen_järjestys; "")`
7.  Laske positiivisten ja negatiivisten järjestysarvojen summat erikseen.
8.  Laske otoskooksi kaikki arvot, jotka saivat järjestysarvon. Jätä siis pois nolla-arvot otoskoosta.
9.  Hae otoskokosi mukaan merkitsevyysraja kriittisten arvojen taulukosta.
    1.  Muista häntäisyys! Jos testisi on kaksihäntäinen, hae pienimmän otoskoon mukaan. Jos testisi on yksihäntäinen, hae sen otoskoon mukaan, jonka merkkiä testaat (negatiivinen, eli alle nollahypoteesin; tai positiivinen, eli yli nollahypoteesin).

[Jos haluat vielä laskea z-arvon merkitsevyyden]{.underline}, jatka tästä:

10. Laske testin keskiarvo.
11. Laske testin keskihajonta.
12. Laske haluttavan häntäisyyden z-arvo.
13. Hae z-arvon p-arvo: `=NORM_JAKAUMA.NORMIT(z; EPÄTOSI)`

### Wilcoxonin testin raportointi {#sec-wilcoxonin-testin-raportointi}

[Wilcoxonin testin suureena käytetään järjestysnumeroiden summaa]{.underline}. Valinta niiden välillä riippuu hypoteesirakennelmastasi/häntäisyydestä. Raportoi ainakin:

-   Testisuure $T$

-   Otoskoko $n$

-   Häntäisyys sekä suunta (jos yksihäntäinen)

-   Testisuureen p-arvo $p$

[Jos laskit z-arvon]{.underline}, alkuperäisen p-arvon sijaan raportoi:

-   että laskit z-arvon!

-   Z-arvo $z$

-   Keskiarvo $\bar{T}$

-   Keskihajonta $\text{SE}$

-   Z-arvon p-arvo $p$

## Mann-Whitney'n U-testi {#sec-mann-whitneyn-u-testi}

**Mittausasteikot:** Järjestysasteikosta ylöspäin

**Mann-Whitney'n U-testi** on ei-parametrinen testi, jolla testataan kahden riippumattoman muuttujan välistä suhdetta. Testi on periaatteessa sama kuin Wilcoxonin testi, mutta toimii siis kahden otoksen vertailussa parittaisten muuttujien sijaan. Testin parametrinen vastaavuus on **kahden otoksen t-testi** (ks. @sec-kahden-otoksen-welchin-t-testi-teoria).

[Myös U-testi voidaan tehdä yksi- tai kaksihäntäisenä]{.underline}; yleisintä on kuitenkin tehdä kaksihäntäinen testi, jolla testataan, eroavatko molemmat ryhmät toisistaan (eli ei testata suuntaa).

[U-testi lasketaan hyvin samoin kuin Wilcoxonin testi]{.underline}, mutta U-testissä testataan, eroavatko kaksi ryhmää toisistaan:

1.  Anna jokaiselle riville järjestysnumero.
2.  Summaa järjestysnumerot molemmille ryhmille erikseen. Pienempi arvo näistä kahdesta on $W$-suure (sama kuin Wilcoxonin testissä), jonka voi raportoida suoraan.
3.  Laske otoskoot molemmille ryhmille.
4.  Laske molemmille ryhmille U-arvot. Pienempi arvo näistä kahdesta raportoidaan.

[W-arvon pohjalta voidaan myös laskea z-arvon]{.underline} ja hakea sen todennäköisyys, kuten Wilcoxonin testille. Toimintamalli on täysin sama.

### Mallioletukset {#sec-mann-whitneyn-u-mallioletukset}

[U-testillä on hieman muita ei-parametrisiä testejä enemmän mallioletuksia]{.underline}, mutta kuitenkin vähemmän kuin lineaarisilla malleilla:

-   **Riippumaton muuttuja tulisi olla dikotominen**, koska testi vertaa kahta ryhmää keskenään. Jos riippumaton muuttuja on monikategorinen, testi tulee tehdä erikseen jokaiselle verratulle ryhmälle. Siinä vaiheessa kuitenkin khiin neliö (@sec-khiin-neliö) voi olla suositeltava (jos riippuvainen muuttuja on luokittelu- tai järjestysasteikolla).

-   **Sama yksikkö ei saa olla molemmissa ryhmissä**. Tällöin sinun tulisi käyttää Wilcoxonin testiä. Jos sinulla on *sekä* parittaisia *että* kahden otoksen rakenteita samaan aikaan, joudut käyttämään mixed-models-menetelmiä.

-   **Otos on satunnaisesti haettu populaatiosta**. Tämä pätee kaikkiin frekvenssitilastotieteellisiin malleihin muutenkin.

### U-testin laskeminen {#sec-u-testin-laskeminen}

[Aloita järjestämällä kaikki arvot järjestykseen]{.underline}; pienin saa järjestysnumeron 1 ja suurin järjestysnumeron $n$.

[Laske sitten järjestysnumeroiden summat ja otoskoot]{.underline} ryhmien perusteella, eli summaa jokaisen ryhmän arvot erikseen.

Pienempi summista on $W$-arvo, jota voidaan käyttää myöhemmin todennäköisyyden laskemiseen.

[Laske W-arvojen U-suureet]{.underline} seuraavalla kaavalla:

$$
\begin{split}
U_1 = n_{k_1} n_{k_2} + \frac{n_{k_1}(n_{k_1}+1)}{2}-W_1
\\ U_2 = n_{k_1} n_{k_2} + \frac{n_{k_2}(n_{k_2}+1)} {2}-W_2
\end{split}
$$ {#eq-u-suure}

Kerro ensin molempien ryhmien otoskoot yhteen. Lisää tähän jakolasku, jossa kerrot ensin ensimmäisen ryhmän otoskoon itsellään plus yksi ja jaat lopputuloksen kahdella. Vähennä vielä tästä ensimmäisen ryhmän $W$-arvo, eli järjestysnumeroiden summa.

Laske $U$-suure molemmille ryhmille erikseen.

Pienempi näistä kahdesta on lopullinen $U$-suure:

$$
U = \min(U_1, U_2)
$$ {#eq-u-suure-2}

Merkitsevyyden laskemiseksi, laske ensin $U$-suureen keskiarvo $\bar{U}$ sekä keskihajonta $\text{SD}_{\bar{U}}$:

$$
\begin{split}
\bar{U} = \frac{n_1 n_2}{2}
\\ \text{SE}_{\bar{U}} = \sqrt{\frac{n_1 n_2 (n_1 + n_2 + 1)}{12}}
\end{split}
$$ {#eq-u-suure-mean-sd}

Keskiarvo $\bar{U}$ on yksinkertaisesti molemmat ryhmäkoot kerrottuna yhteen ja jaattuna kahdella. Keskihajonnassa $\text{SE}_{\bar{U}}$ kerrot ryhmäkoot yhteen, kerrot tämän tuloksen ryhmäkokojen yhteensummauksella plus yksi, jaat tuloksen 12:lla ja otat viimeisen tuloksen neliöjuuren.

[Laske sitten z-arvo]{.underline}:

$$
z_U = \frac{U-\bar{U}}{\text{SD}_{\bar{U}}}
$$ {#eq-w-suure-z-normalisointi}

jossa $U$ on pienempi kahdesta $U$-suureesta (@eq-u-suure-2), $\bar{U}$ on aikaisemmin laskettu keskiarvo ja $\text{SD}_{\bar{U}}$ aikaisemmin laskettu keskihajonta.

[Lopputuloksen z-arvon voit tarkistaa kriittisten arvojen taulukosta tai laskurilla]{.underline}.

### U-testin toteuttaminen Excelissä {#sec-u-testin-toteuttaminen-excelissä}

Tunnistat varmaan käytännön tässä vaiheessa - [U-testi tehdään käsin Excelissä]{.underline}. Toimintatapa on hyvin samankaltainen kuin muille:

1.  Määrittele hypoteesipari ja häntäisyys.
2.  Hae molempien ryhmien data eriteltynä sarakkeisiin (tämä helpoittaa analyysia myöhemmin): `=SUODATA(testattava_muuttuja; ryhmämuuttuja = ryhmänumero)` molemmille ryhmille.
    1.  Jos testattavalla muuttujalla on tyhjiä arvoja, muista poistaa myös ne ennen suodatusta - muuten Excel korvaa ne nollalla! Esim.: `=SUODATA( testattava_muuttuja; (ryhmämuuttuja = ryhmänumero) * (testattava_muuttuja <> "") )`
3.  Laske ryhmien järjestysnumerot yhtenä pakettina, mutta eriteltynä ryhmäsarakkeisiin:
    1.  Tee kaksi saraketta, yksi jokaisen ryhmän järjestysarvoille, samassa järjestyksessä kuin haettu data. (ensimmäinen ryhmä vasemmalla toisesta ryhmästä).
    2.  Laske ensimmäiseen soluun `=ARVON.MUKAAN.KESKIARVO(järjestettävä_arvo; järjestysalue; 1)`. Huomaa, että järjestysalueeksi määrittelet molemmat muuttujat, et vain yhden niistä!
        1.  Jos olet käyttänyt suodatusfunktiota yllä, voit viitata alueiden kokoon risuaidoilla. Jos esim. ryhmätiedot löytyvät alueilta `I2:I113` ja `J2:J124` (eli ovat erikokoisia), viittauksen voi tehdä muodossa `I2#:J2#`.
    3.  Lukitse järjestysalue (esim. `$I$2#:$J$2#`).
    4.  Monista funktio vetotoiminnolla molempiin sarakkeisiin kaikille riveille.
4.  Laske järjestysnumerosarakkeiden summat (`SUMMA`) ja otoskoot (`LASKE` tai `LASKE.A`).
5.  Laske ryhmien U-koot:
    1.  Ryhmä 1: `=n_1 * n_2 + n_1 * (n_1 + 1) / 2 - W_1`
    2.  Ryhmä 2: `=n_1 * n_2 + n_2 * (n_2 + 1) / 2 - W_2`
6.  Laske U-suure: `=min(U_1; U_2)`

Olet valmis U-suureen laskemisessa! [Jos haluat laskea z-arvon]{.underline} ja hakea sen todennäköisyyden, jatka tästä.

6.  Laske U-suureen keskiarvo: `=(n_1 * n_2) / 2`
7.  Laske U-suureen keskihajonta: `=NELIÖJUURI( (n_1 * n_2 * (n_1 + n_2 + 1) ) / 12)`
8.  Laske z-arvo: `=(u - u_keskiarvo) / u_keskihajonta`
9.  Hae z-arvon todennäköisyys:
    6.  Yksihäntäinen: `=NORM_JAKAUMA.NORMIT(z; TOSI)`
    7.  Kaksihäntäinen: `=NORM_JAKAUMA.NORMIT(z; TOSI) * 2`

### U-testin raportoiminen {#sec-u-testin-raportoiminen}

U-testissä itse U-suure on testisuure. Raportoi täten mieluisesti:

-   Ryhmien mediaanit $\text{Md}$

-   U-suure $U$

-   Molempien ryhmien otoskoot $n_1$ ja $n_2$

-   Z-arvo $z$ ja sen p-arvo $p$

## Spearmanin rho $\rho$ {#sec-spearmanin-rho-teoria}

**Mittausasteikot:** Molemmat muuttujat järjestysasteikolla.

**Spearmanin rho** $\rho$ tai **Spearmanin korrelaatiokerroin** $r_s$ on ei-parametrinen korrelaatiokerroin. Sen parametrinen vastaavuus on **Pearsonin** $r$ (ks. @sec-korrelaatio-teoria).

Spearmanin rho toimii kuten Pearsonin $r$, mutta sen sijaan, että testi laskettaisiin suoraan kovarianssista, se lasketaan datapisteiden **järjestysnumeroilla**.

[Spearmanin rho on robustimpi kuin Pearsonin]{.underline} $r$, eikä siihen vaikuta esim. ääripääarvot samalla tavalla. Koska rho lasketaan järjestysnumeroille eikä datalle suoraan, sitä voi myös käyttää järjestysasteikon muuttujilla.

[Jos muuttujasi täyttävät Pearsonin]{.underline} $r$[-testin vaatimuksia]{.underline}, käytä sitä mielummin. Jos datassasi on kuitenkin suuria ääripääarvoja, on epälineaarista tai muuten rikkoo Pearsonin korrelaatiokertoimen malliodotuksia (ks. @sec-korrelaatiokertoimen-mallioletukset), voit käyttää Spearmanin testiä Pearsonin testin sijaan.

### Mallioletukset {#sec-mallioletukset-spearmanin-rho}

Spearmanin rho ei riipu yleisistä lineaaristen mallien oletuksista (koska se ei ole lineaarinen malli), mutta sillä on kolme omaa oletusta: **muuttujatasot** sekä **monotonisuus**:

-   [Muuttujien tulee olla vähintään järjestystasolla]{.underline} (järjestys-, välimatka- tai suhdeasteikko). Spearmanin rhota ei voi laskea luokitteluasteikolle, koska muuttujia ei voi silloin laittaa luonnolliseen järjestykseen.

-   [Muuttujien tulee olla monotonisessa suhteessa toisiinsa]{.underline}. Monotonisuus tarkoittaa, että muuttujien suhde joko nousee tai laskee. Kaikki lineaariset mallit ovat monotonisia, mutta monotoniset mallit eivät tarvitse olla lineaarisia. Esimerkiksi eksponentiaalinen tai logaritminen suhde on monotoninen mutta epälineaarinen. Parabolisuhde toisaalta ei ole lineaarinen eikä monotoninen, koska sen suunta muuttuu kesken käyrän. Toisin sanoen: [Spearmanin rho voi mallintaa epälineaarisia suhteita, kunhan ne eivät muutu suunnassaan kesken kaiken.]{.underline}

[Näiden lisäksi Spearmanin rhon laskutapa riippuu siitä, esiintyykö muuttujilla tasajärjestyksiä vai ei]{.underline}. **Tasajärjestys** määritellään kuin Wilcoxonin signed-rank -testille: tasajärjestys esiintyy kun kaksi tai useampi arvo saisi saman järjestysarvon, jolloin laskemme niiden keskiarvon.

### Spearmanin rhon laskeminen {#sec-spearmanin-rhon-laskeminen}

[Spearmanin rhon laskeminen seuraa hyvin samanlaista logiikkaa]{.underline} kuin Pearsonin korrelaatiokerroin, mutta data pitää ensin järjestää:

-   Laske järjestysnumerot molemmille muuttujille erikseen.

    -   Valitse rhon laskukaava sen mukaan, esiintyykö tasajärjestyksiä vai ei.

-   Laske Spearmanin rho-suure.

[Jos muuttujilla ei ole tasajärjestyksiä]{.underline}, käytä seuraavaa kaavaa:

$$
\rho = 1-\frac{6\sum{d_i^2}}{n^3-n}
$$ {#eq-spearman-01}

Laske ensin jokaisen rivin erot muuttujien järjestysarvojen välillä, $d_i$ (jossa $i$ on rivin numero). Laske sitten jokaiselle erolle neliö $d_i^2$ ja summaa kaikki neliöt yhteen. Kerro tulos kuudella.

Jakolaskun alaosassa, laske otoskoon kuutio $n^3$ ja vähennä siitä otoskoko $n$.

Jaa sitten ensimmäiseksi laskettu erotuksen neliösumma toiseksi lasketulla otoskokomitalla. Vähennä lopullinen tulos yhdestä - saat Spearmanin rhon $\rho$.

[Jos muuttujilla on tasajärjestyksiä]{.underline}, käytä vaihtoehtoista kaavaa:

$$
\rho = \frac{ 1/n \sum{(x_i - \bar{x}) \times (y_i - \bar{y})} } { \sqrt{( 1/n \sum{(x_i - \bar{x})^2} ) \times (1/n \sum{(y_i - \bar{y})^2}) } }
$$ {#eq-spearman-02}

Myönnetään, tämä laskukaavio on aika hirvittävä. Kyseiset merkinnät ovat käytössä:

-   $x_i$ ja $y_i$ ovat muuttujien järjestysarvot rivillä $i$

-   $\bar{x}$ ja $\bar{y}$ ovat muuttujien järjestysarvojen keskiarvot

-   $n$ on koko otoksen otoskoko

-   $1/n$ on otoskoon inverssi; jonkun luvun kertominen tällä on sama kuin luvun jakaminen otoskoolla $n$: $1/n \times 5 = 5/n$

[Laskutoiminto soveltaa Pearsonin korrelaatiokertoimen laskukaaviota]{.underline}, mutta korvaa datan alkuperäisluvut järjestysluvuilla. Toisin sanoen: kaava on tismalleen sama kuin Pearsonin kaava, paitsi että käytetyt luvut ovat järjestyslukuja.

[Rho-suure tulkitaan kuten Pearsonin]{.underline} $r$[-suuretta]{.underline}.

[Jos haluat laskea merkitsevyyden]{.underline}, laske ensin rho-suureen t-arvo:

$$
t = r\sqrt{\frac{n-2}{1-r^2}}
$$ {#eq-spearman-04}

Laske ensin t-jakauman vapausasteet $n-2$, sitten rho-suureen neliö $r^2$ ja sen inverssi $1-r^2$. Jaa vapausasteet tällä inverssillä, ja ota tuloksen neliöjuuri. Kerro viimeiseksi neliöjuuren tulos rho-suurella $r$. Lopputulos on t-suure, joka seuraa Studentin t-jakaumaa vapausasteilla $n-2$. Voit hakea todennäköisyysarvon t-suureelle kaksihäntäisen kriittisten arvojen taulukolla tai laskurilla.

### Spearmanin rhon laskeminen Excelissä {#sec-spearmanin-rhon-laskeminen-excelissä}

Vaikka yllä olevat kaavat näyttävät aika monimutkaisilta, voimme onneksi tehdä Spearmanin rho-testin paljon yksinkertaisemmin Excelissä.

[Meidän ei nimittäin tarvitse välittää ollenkaan tasajärjestyksistä]{.underline} - koska Spearmanin rho-lasku on loppujen lopuksi vain Pearsonin korrelaatiokerroin, mutta laskettu järjestysluvuilla eikä alkuperäisillä luvuilla!

Laskutoimitus seuraa tätä prosessia:

1.  Laske molempien muuttujien järjestysarvot:
    1.  Muuttuja 1: `=ARVON.MUKAAN.KESKIARVO(ensimmäinen_solu_m1; muuttuja_1; 0)`.
    2.  Muuttuja 2: `=ARVON.MUKAAN.KESKIARVO(ensimmäinen_solu_m2; muuttuja_2; 0)`.
    3.  Lukitse muuttujamääritelmät (`muuttuja_1` ja `muuttuja_2`).
    4.  Vedä funktiot kaikkien rivien yli vetotoiminnolla.
2.  Laske järjestyslukualueiden korrelaatiokerroin: `=KORRELAATIO(järjestys_m1; järjestys_m2)`. Huomaa, että alueina pitää olla järjestysluvut, ei alkuperäiset luvut!
3.  Laske t-suure: `=r * NELIÖJUURI( (n - 2) / (1 - r^2) )`.
4.  Laske t-suureen vapausasteet: `=n - 2`.
5.  Hae kaksihäntäinen todennäköisyysarvo: `=T.JAKAUMA.2S(t; vapausasteet)`.

### Spearmanin rhon raportointi {#sec-spearmanin-rhon-raportointi}

Raportoi rho-testistä mieluisesti seuraavat:

-   Spearmanin testisuure $\rho$ (vaihtoehtoisesti kirjoitettuna $r_s$)

-   T-suure $t$ ja sen vapausasteet $\text{df}$

-   Merkitsevyys $p$

## Testikoot ei-parametrisille testeille {#sec-testikoot-ei-parametrisille-testeille}

[Yleisesti ottaen pitää aina raportoida mediaanit]{.underline}, joita on tarkasteltu. Ryhmävertailussa raportoidaan ryhmien mediaanit; yhden otoksen testissä otoksen mediaani. Näiden lisäksi on hyvä raportoida myös [nollahypoteesi sekä vaihtoehtohypoteesi]{.underline}.

Niille testeille, joille lasket z-arvon, [voit myös laskea Pearsonin]{.underline} $r$[-arvon]{.underline} saadaksesi testikoon jota voi verrata muihin testeihin. Sen laskeminen on hyvin yksinkertaista:

$$
r = \frac{z}{\sqrt{n}}
$$ {#eq-r-suure-z-testistä}

Jaa siis z-arvo otoskoon neliöjuurella. Otoskoolla tarkoitetaan sitä kokoa, jota käytit laskeaksesi z-arvon. Yleensä tämä on koko mittauksen otoskoko. Parittaiselle testille kyseessä on kaksi kertaa ryhmän koko (poislukien nolla-arvot). Jos alkuperäinen otos oli 10 yksikköä, ja mitasta poistui kaksi nolla-arvoa, otoskoko on $2*8 = 16$.

$r$-suure raportoidaan samassa kohdassa kuin muut raportoitavat tiedot.
