<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fi" xml:lang="fi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Kvantitatiiviset menetelmät -kurssin verkkokirja - 13&nbsp; Excelin perusteet</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./excelinkäyttöliittymä.html" rel="next">
<link href="./pics/logo_lapinakyva.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Ei tuloksia",
    "search-matching-documents-text": "tulokset",
    "search-copy-link-title": "Kopioi linkki hakuun",
    "search-hide-matches-text": "Piilota loput tulokset",
    "search-more-match-text": "tulos tässä dokumentissa",
    "search-more-matches-text": "tulosta tässä dokumentissa",
    "search-clear-button-title": "Tyhjennä",
    "search-detached-cancel-button-title": "Peruuta",
    "search-submit-button-title": "Lähetä",
    "search-label": "Hae"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Kvantitatiiviset menetelmät -kurssin verkkokirja - 13&nbsp; Excelin perusteet">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="pics/viittaaminen/viit_esimerkki01a.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Kvantitatiiviset menetelmät</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Hae"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Vaihda navigointi" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Aluksi</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ohjeita" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Ohjeita</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ohjeita">    
        <li>
    <a class="dropdown-item" href="./visualisoinninalkeet.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualisoinnin alkeet</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ohjeitaviittaamiseen.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ohjeita viittaamiseen</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tilastotiede" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Tilastotiede</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tilastotiede">    
        <li>
    <a class="dropdown-item" href="./mittaustasot.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Muuttuja ja mittaustasot</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hypoteesitestaus.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypoteesitestaus</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mallioletukset.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mallioletukset ja virhe</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sijaintiluvut.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sijaintiluvut</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hajontaluvut.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hajontaluvut</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./merkitsevyysluvut.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Merkitsevyysluvut</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./eiparametrisettestit.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Ei-parametriset testit</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ttesti.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">T-testi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./korrelaatio.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Korrelaatio</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./khiinneliö.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Khiin neliö <span class="math inline">\(\chi^2\)</span></span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-excel-toiminnot" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Excel-toiminnot</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-excel-toiminnot">    
        <li>
    <a class="dropdown-item" href="./excelinperusteet.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Excelin perusteet</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./excelinkäyttöliittymä.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Excelin käyttöliittymä</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nimeäminenexcelissä.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Nimeäminen Excelissä</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./yleisiätoimintoja.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Yleisiä toimintoja Excelissä</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./excelgrafiikka.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Grafiikka Excelissä</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./funktiot.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Funktiot</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lambdakaavat.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">LAMBDA-kaavoja</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-työkalut" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Työkalut</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-työkalut">    
        <li>
    <a class="dropdown-item" href="./webropol.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Webropol</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tilastotyökalut.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Tilastotyökalut</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dmptuuli.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">DMPTuuli</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tietoarkistot.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Tietoarkistot</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./zotero.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Zotero-lähdehallintatyökalu</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./viiteluettelo.html" rel="" target="">
 <span class="menu-text">Viiteluettelo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./history.html" rel="" target="">
 <span class="menu-text">Päivityshistoria</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
    <a href="https://github.com/osaal/KVANT-23-PEO/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Vaihda sivupalkki" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./excelinperusteet.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Excelin perusteet</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Vaihda sivupalkki" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-end sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./pics/logo_nimi_nega.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excelinperusteet.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Excelin perusteet</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excelinkäyttöliittymä.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Excelin käyttöliittymä</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nimeäminenexcelissä.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Nimeäminen Excelissä</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./yleisiätoimintoja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Yleisiä toimintoja Excelissä</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excelgrafiikka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Grafiikka Excelissä</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./funktiot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Funktiot</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lambdakaavat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">LAMBDA-kaavoja</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Sisällysluettelo</h2>
   
  <ul>
  <li><a href="#sec-arvotyypit" id="toc-sec-arvotyypit" class="nav-link active" data-scroll-target="#sec-arvotyypit"><span class="header-section-number">13.1</span> Arvotyypit</a></li>
  <li><a href="#sec-arvojen-manipulointi-excelissä" id="toc-sec-arvojen-manipulointi-excelissä" class="nav-link" data-scroll-target="#sec-arvojen-manipulointi-excelissä"><span class="header-section-number">13.2</span> Arvojen manipulointi Excelissä</a></li>
  <li><a href="#sec-loogisten-ehtojen-totuustaulukot" id="toc-sec-loogisten-ehtojen-totuustaulukot" class="nav-link" data-scroll-target="#sec-loogisten-ehtojen-totuustaulukot"><span class="header-section-number">13.3</span> Loogisten ehtojen totuustaulukot</a></li>
  <li><a href="#sec-solujen-muokkaaminen" id="toc-sec-solujen-muokkaaminen" class="nav-link" data-scroll-target="#sec-solujen-muokkaaminen"><span class="header-section-number">13.4</span> Solujen muokkaaminen</a></li>
  <li><a href="#sec-viittaaminen-ja-osoitteet" id="toc-sec-viittaaminen-ja-osoitteet" class="nav-link" data-scroll-target="#sec-viittaaminen-ja-osoitteet"><span class="header-section-number">13.5</span> Viittaaminen ja osoitteet</a></li>
  <li><a href="#sec-vetotoiminto" id="toc-sec-vetotoiminto" class="nav-link" data-scroll-target="#sec-vetotoiminto"><span class="header-section-number">13.6</span> Vetotoiminto</a></li>
  <li><a href="#sec-lukitustoiminto" id="toc-sec-lukitustoiminto" class="nav-link" data-scroll-target="#sec-lukitustoiminto"><span class="header-section-number">13.7</span> Lukitustoiminto</a></li>
  <li><a href="#sec-funktiot-teoria" id="toc-sec-funktiot-teoria" class="nav-link" data-scroll-target="#sec-funktiot-teoria"><span class="header-section-number">13.8</span> Funktiot</a></li>
  <li><a href="#sec-dynaamiset-matriisit" id="toc-sec-dynaamiset-matriisit" class="nav-link" data-scroll-target="#sec-dynaamiset-matriisit"><span class="header-section-number">13.9</span> Dynaamiset matriisit</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/osaal/KVANT-23-PEO/issues/new" class="toc-action">Ilmoita ongelmasta</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-excelin-perusteet" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Excelin perusteet</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="page-columns page-full"><p>Microsoft Excel on <strong>taulukkolaskentaohjelma</strong>. Tällä tarkoitetaan, että kaikki työ tehdään <strong>taulukoissa</strong>, joita Excel kutsuu myös <strong>työkirjoiksi</strong>. Työkirjan tunnistaa päätteestä <code>.xlsx</code><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Jokainen työkirja sisältää yhden tai useamman <strong>työlehtiön</strong>, joiden sisältä löytyy <strong>taulukkoalue</strong>.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Aikaisemmissa Excel-versioissa myös <code>.xls</code>. Toinen yleinen taulukkomuoto on <code>.csv</code>.</p></li></div></div>
<p>Taulukkoalue jaetaan <strong>soluihin</strong>, joilla on <strong>rivi- ja sarakeosoitteet</strong>. Excelissä rivit ovat numeroituna yhdestä ylöspäin, ja sarakkeet merkitään kirjaimilla A-Z. Jos sarakkeita on useampi kuin 26, Excel automaattisesti aloittaa seuraavan sarakesarjan nimen AA, AB, ja niin eteenpäin.</p>
<p><u>Excelissä kaikki työ tehdään taulukkoalueella</u>. Voit lisätä ja poistaa <strong>arvoja</strong> (numeroita, tekstiä, verkko-osoitteita, melkein mitä tahansa), tehdä laskentoja arvoille, tuottaa kuvioita, automatisoida analyysia, ja vaikka mitä.</p>
<section id="sec-arvotyypit" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="sec-arvotyypit"><span class="header-section-number">13.1</span> Arvotyypit</h2>
<p>Excelissä on neljä <strong>alkeellista</strong> arvo- tai datatyyppiä: numerot, teksti, loogiset ja virheet.</p>
<p><strong>Numerodata</strong> on, kuten nimi ehdottaa, numeroita. Ne voivat olla desimaalilukuja (esim. <code>0.5</code>), kokonaislukuja (<code>13</code>), prosentteja (<code>15%</code>), päivämääriä (<code>16/03/2005</code>) tai jopa puhelinnumeroita (<code>0501234567</code>). Koska Exceliä ei sinänsä kiinnosta millainen numeroarvo on kyseessä, voi joskus sattua hassuja odottamattomuuksia. Excel antaa esimerkiksi sinun ynnätä päivämäärän ja prosentin yhteen - mutta mitä tulos on, sen tietää vain Excel itse.</p>
<p><strong>Tekstidata</strong> on ihmisluettavaa tekstiä, kuten lauseita, sanoja, merkkejä tai fyysisiä osoitteita. Näille löytyy omat työkalut Excelissä, joten pystyt myös käsittelemään tekstidataa koneella Excelissä.</p>
<p><strong>Loogisia arvoja tai totuusarvoja</strong> ovat arvot <code>TOSI</code> ja <code>EPÄTOSI</code>. Näitä käytetään paljon Excelissä, myöskin funktioiden sisällä, joten niiden tunnistaminen on tärkeää. Jos yrität ynnätä loogisia arvoja yhteen, Excel yleensä pakottaa ne numeromuotoon: <code>TOSI = 1, EPÄTOSI = 0</code>. Loogisille arvoille löytyy neljä perustoimintoa: <code>JA, TAI, EHDOTON.TAI, EI</code>. Näistä lisää <a href="#sec-loogisten-ehtojen-totuustaulukot">alaluvussa&nbsp;<span>13.3</span></a>.</p>
<p><strong>Virhearvot</strong> ovat Excelin erikoisuus. Jos Excel tunnistaa jonkun laskuvirheen tai muun teknisen virheen, se palauttaa yleensä virhearvon. Näitä voi myös itse tuottaa virhearvofunktioilla, jos siihen on tarvetta. Virhearvot ovat:</p>
<ul>
<li><p><strong>#NIMI?</strong> Soluviittaus ei ole oikein, kirjoitusvirhe funktiossa tai puuttuvat lainausmerkit.</p></li>
<li><p><strong>#JAKO/0</strong> Yrität jakaa jonkun numeron nollalla, mikä ei ole mahdollista.</p></li>
<li><p><strong>#VIITE!</strong> Viittaus menee jotenkin pieleen.</p></li>
<li><p><strong>#NUMERO!</strong> Arvo, jonka Excel yrittää laskea, on liian iso yhdelle solulle. Voi myös esiintyä virheellisesti kirjoitetussa funktiossa.</p></li>
<li><p><strong>#N/A</strong> Voit käyttää tätä arvoa itse, jos haluat Excelin hyppäävän yli jonkun solun tilapäisesti. Joskus Excel myös automaattisesti korvaa tämän arvon jollain muulla. Ole siis varovainen sen käytön kanssa!</p></li>
<li><p><strong>#ARVO!</strong> Yrität tehdä jotain arvotyypille, jota sille ei voi tehdä. Esimerkiksi ynnäät tekstiä ja numeroita yhteen.</p></li>
<li><p><strong>#TYHJÄ!</strong> Yrität hakea kahden matriisin risteämiskohtia, mutta sellaista ei ole. Esiintyy myös jos merkitset useamman solualueen ilman puolipilkkua välissä, sekä joissain muissa tilanteissa.</p></li>
</ul>
</section>
<section id="sec-arvojen-manipulointi-excelissä" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="sec-arvojen-manipulointi-excelissä"><span class="header-section-number">13.2</span> Arvojen manipulointi Excelissä</h2>
<p>“Manipulointi” voi kuulostaa pahaenteiseltä, mutta sanalla tarkoitetaan vain arvojen muokkaamista, muuttamista ja hyödyntämistä laskennoissa.</p>
<p><u>Excelin operaattorit voidaan jakaa neljään kategoriaan</u>: <strong>aritmeettiset</strong>, <strong>vertailevat</strong>, <strong>tekstiä yhdistävät</strong> ja <strong>viittausoperaattorit</strong>. Alla olevassa taulukossa selitetään kaikki operaattorit ja niiden toiminnat.</p>
<div id="tbl-excelin-operaattorit" class="anchored">
<table class="table">
<caption>Taulukko&nbsp;13.1: Excelin operaattorit</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 38%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Merkki</th>
<th>Merkitys</th>
<th>Esimerkki</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Aritmeettiset operaattorit</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>+</code> (plus)</td>
<td>Ynnääminen</td>
<td><code>2 + 3 = 5</code></td>
</tr>
<tr class="odd">
<td><code>-</code> (minus)</td>
<td>Vähentäminen</td>
<td><code>2 - 5 = -3</code></td>
</tr>
<tr class="even">
<td><code>*</code> (tähti)</td>
<td>Kertominen</td>
<td><code>4 * 2 = 8</code></td>
</tr>
<tr class="odd">
<td><code>/</code> (vinoviiva)</td>
<td>Jakaminen</td>
<td><code>8 / 4 = 2</code></td>
</tr>
<tr class="even">
<td><code>%</code> (prosentti)</td>
<td>Prosentti</td>
<td><code>20%</code></td>
</tr>
<tr class="odd">
<td><code>^</code> (karetti)</td>
<td>Potenssi</td>
<td><code>5 ^ 2 = 25</code></td>
</tr>
<tr class="even">
<td><strong>Vertailevat operaattorit</strong></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>=</code> (yhtäläisyys)</td>
<td>Yhtä kuin</td>
<td><code>1 = 2</code> (epätosi)</td>
</tr>
<tr class="even">
<td><code>&gt;</code> (suuruus)</td>
<td>Suurempi kuin</td>
<td><code>5 &gt; 1</code> (tosi)</td>
</tr>
<tr class="odd">
<td><code>&lt;</code> (pienuus)</td>
<td>Pienempi kuin</td>
<td><code>6 &lt; 9</code> (tosi)</td>
</tr>
<tr class="even">
<td><code>&gt;=</code> (suuruus ja yhtäläisyys)</td>
<td>Suurempi tai yhtä kuin</td>
<td><code>1 &gt;= 2</code> (epätosi)</td>
</tr>
<tr class="odd">
<td><code>&lt;=</code> (pienuus ja yhtäläisyys)</td>
<td>Pienempi tai yhtä kuin</td>
<td><code>6 &lt;= 6</code> (tosi)</td>
</tr>
<tr class="even">
<td><code>&lt;&gt;</code> (pienuus ja suuruus)</td>
<td>Ei yhtä kuin / eri kuin</td>
<td><code>7 &lt;&gt; 9</code> (tosi)</td>
</tr>
<tr class="odd">
<td><strong>Tekstiä yhdistävät operaattorit</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>&amp;</code> (ampersandi)</td>
<td>Yhdistää kaksi tekstiarvoa yhdeksi. Ei lisää välilyöntejä tai muita merkkejä väliin!</td>
<td><code>"Pelastus"&amp;"laitos" = "Pelastuslaitos"</code></td>
</tr>
<tr class="odd">
<td><strong>Viiteoperaattorit</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>:</code> (kaksoispiste)</td>
<td>Solualue</td>
<td><code>A1:A4 = A1, A2, A3, A4</code></td>
</tr>
<tr class="odd">
<td><code>;</code> (puolipilkku)</td>
<td>Yhdistää kaksi solualuetta yhdeksi</td>
<td><code>A1:A3;B1:B3 = A1, A2, A3, B1, B2, B3</code></td>
</tr>
<tr class="even">
<td>(välilyönti)</td>
<td>Hakee kahden solualueen yhteisen alueen viitteen</td>
<td><code>A1:D1 C1:C4 = C1</code> (ainoa solu, joka löytyy molemmista janoista)</td>
</tr>
<tr class="odd">
<td><code>#</code> (risuaita)</td>
<td>Viittaa dynaamiseen matriisiin</td>
<td><code>A1#</code> = Niin monta solua, kuin dynaaminen funktio solussa <code>A1</code> tuottaa</td>
</tr>
<tr class="even">
<td><code>!</code> (huutomerkki)</td>
<td>Ilmaisee solualueen sijaitsevan jossain muualla</td>
<td><code>Taul1!A1</code> hakee solun <code>A1</code> työlehtiöstä <code>Taul1</code>, vaikka olisit työlehtiössä <code>Taul4</code>.</td>
</tr>
</tbody>
</table>
</div>
<p>Näiden lisäksi Excelissä voi käyttää sulkuja <code>( )</code> laskentajärjestyksen määrittelyyn. Tämä on erittäin suositeltavaa, sillä <strong>Excel ei aina noudata perinteistä laskentajärjestystä</strong>! Excel laskee vasemmalta oikealle, tietyn suosiojärjestyksen mukaan. Voit kuitenkin aina itse määritellä järjestyksen suluilla.</p>
<p><strong>Aritmeettisia ja vertailevia operaattoreita</strong> käytetään kuten matematiikassa yleensä. Huomioi kuitenkin eri-kuin-operaattori <code>&lt;&gt;</code>, joka muotoillaan eri tavalla kuin monessa muussa kontekstissa.</p>
<p>Kun määrittelet soluun jotain laskettavaksi, eteen tulee aina <strong>yhtäläisyysmerkki</strong> <code>=</code>. Tämä kertoo Excelille, että seuraavaksi lasketaan jotain.</p>
<p>Huomaa vielä, että <strong>viiteoperaattort</strong> voivat toimia hieman eri tavoin riippuen käyttökontekstista. Esimerkkinä puolipilkku: puolipilkkua käytetään funktioiden parametrien erittelyssä (ks. alla) suomenkielisessä Excelissä, jolloin se ei yhdistä matriisialueita funktion sisällä.</p>
</section>
<section id="sec-loogisten-ehtojen-totuustaulukot" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="sec-loogisten-ehtojen-totuustaulukot"><span class="header-section-number">13.3</span> Loogisten ehtojen totuustaulukot</h2>
<p>Kun käsittelemme loogisia ehtoja, voimme hyödyntää niin sanottuja <strong>totuustaulukoita</strong>. Nämä kertovat meille, mikä lopputulos on kun kaksi totuusarvoa yhdistetään tietyllä ehdolla.</p>
<p><code>JA</code>-ehto täyttyy, kun molemmat totuusarvot ovat <code>TOSI</code>. Sen totuustaulukko on:</p>
<div id="tbl-ja-totuus" class="anchored">
<table class="table-striped table-hover table">
<caption>Taulukko&nbsp;13.2: <code>JA</code>-ehdon totuustaulukko</caption>
<tbody>
<tr class="odd">
<td><strong><code>JA</code>-ehto</strong></td>
<td><code>a = EPÄTOSI</code></td>
<td><code>a = TOSI</code></td>
</tr>
<tr class="even">
<td><code>b = EPÄTOSI</code></td>
<td><code>EPÄTOSI</code></td>
<td><code>EPÄTOSI</code></td>
</tr>
<tr class="odd">
<td><code>b = TOSI</code></td>
<td><code>EPÄTOSI</code></td>
<td><code>TOSI</code></td>
</tr>
</tbody>
</table>
</div>
<p><code>TAI</code>-ehto täyttyy, kun jompikumpi totuusarvoista on <code>TOSI</code> (tai molemmat). Sen totuustaulukko on:</p>
<div id="tbl-tai-totuus" class="anchored">
<table class="table-striped table-hover table">
<caption>Taulukko&nbsp;13.3: <code>TAI</code>-ehdon totuustaulukko</caption>
<tbody>
<tr class="odd">
<td><strong><code>TAI</code>-ehto</strong></td>
<td><code>a = EPÄTOSI</code></td>
<td><code>a = TOSI</code></td>
</tr>
<tr class="even">
<td><code>b = EPÄTOSI</code></td>
<td><code>EPÄTOSI</code></td>
<td><code>TOSI</code></td>
</tr>
<tr class="odd">
<td><code>b = TOSI</code></td>
<td><code>TOSI</code></td>
<td><code>TOSI</code></td>
</tr>
</tbody>
</table>
</div>
<p><code>EHDOTON.TAI</code>-ehto täyttyy, kun jompikumpi totuusarvoista on <code>TOSI</code> (mutta ei molemmat!). Sen totuustaulukko on:</p>
<div id="tbl-ehdotontai-totuus" class="anchored">
<table class="table-striped table-hover table">
<caption>Taulukko&nbsp;13.4: <code>EHDOTON.TAI</code>-ehdon totuustaulukko</caption>
<tbody>
<tr class="odd">
<td><strong><code>EHDOTON.TAI</code>-ehto</strong></td>
<td><code>a = EPÄTOSI</code></td>
<td><code>a = TOSI</code></td>
</tr>
<tr class="even">
<td><code>b = EPÄTOSI</code></td>
<td><code>EPÄTOSI</code></td>
<td><code>TOSI</code></td>
</tr>
<tr class="odd">
<td><code>b = TOSI</code></td>
<td><code>TOSI</code></td>
<td><code>EPÄTOSI</code></td>
</tr>
</tbody>
</table>
</div>
<p><code>EI</code>-ehto täyttyy, kun annettu ehto on <code>EPÄTOSI</code>. Toisin sanoen, tämä ehto kääntää totuusarvon toisinpäin. Sen totuustaulukko on:</p>
<div id="tbl-ei-totuus" class="anchored">
<table class="table-striped table-hover table">
<caption>Taulukko&nbsp;13.5: <code>EI</code>-ehdon totuustaulukko</caption>
<tbody>
<tr class="odd">
<td><strong><code>EI</code>-ehto</strong></td>
<td><code>a = EPÄTOSI</code></td>
<td><code>a = TOSI</code></td>
</tr>
<tr class="even">
<td></td>
<td><code>TOSI</code></td>
<td><code>EPÄTOSI</code></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-solujen-muokkaaminen" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="sec-solujen-muokkaaminen"><span class="header-section-number">13.4</span> Solujen muokkaaminen</h2>
<p>Jos klikkaat mitä tahansa solua, solun ympärille syntyy <strong>vihreä valintalaatikko</strong>. Voit valita useamman solun vetämällä hiiren solujen yli, jolloin Excel maalaa kaikki valitsemasi solut tummanharmaalla ja osoittaa solujen valinnan suuremmalla valintalaatikolla.</p>
<p>Voit myös valita soluja näppäimistökomennoilla. Nämä ovat erittäin hyödyllisiä varsinkin tilanteissa, joissa haluat valita suuren määrän soluja kerralla (esim. 400 riviä ja 15 saraketta - kyllä, tämä tilanne tulee helposti vastaan!). Komennot ovat:</p>
<ul>
<li><p>Nuolinäppäimet <code>Ylös</code>, <code>Alas</code>, <code>Vasen</code> ja <code>Oikea</code>: Siirry solualueella nuolen osoittamaan suuntaan.</p></li>
<li><p><code>Shift + Nuolinäppäimet</code>: Lisää seuraava solu nuolen osoittamassa suunnassa valintaasi.</p></li>
<li><p><code>Ctrl + Nuolinäppäimet</code>: Siirry seuraavaan soluun nuolen osoittamassa suunnassa, jossa on tietoja.</p>
<ul>
<li><p>Jos kaikki solut nuolen osoittamassa suunnassa ovat tyhjiä, Excel hyppää taulukon maksimirajaan (rivi 1 048 576, sarake XFD).</p></li>
<li><p>Jos nykyisessä valitussa solussa on dataa, Excel siirtyy viimeiseen soluun nuolen osoittamassa suunnassa, jossa on dataa. Jos esim. olet laittanut numeroita soluihin A1, A2 ja A3, valitset solun A1 ja painat <code>Ctrl + Alas</code>, Excel hyppää soluun A3, koska se on viimeinen alla oleva solu josta löytyy dataa. Jos painat saman yhdistelmän uudelleen, Excel hyppää seuraavaan soluun, josta löytyy dataa. Jos sellaista ei ole, Excel hyppää viimeiselle mahdolliselle riville taulukossa.</p></li>
<li><p>Jos nykyisessä valitussa solussa ei ole dataa, Excel siirtyy seuraavaan soluun nuolen osoittamassa suunnassa, jossa on dataa - tai viimeiselle mahdolliselle riville, jos dataa ei ollenkaan esiinny.</p></li>
</ul></li>
<li><p><code>Shift + Ctrl + Nuolinäppäimet</code>: Lisää kaikki dataa sisältävät solut nuolen osoittamassa suunnassa valintaan.</p>
<ul>
<li>Jos haluat valita ison taulukkoalueen kerralla, tämä on erinomainen komento. Sen sijaan, että valitset solun jostain taulukon nurkasta ja vedät hiiren vastakkaiseen nurkkaan, voit valita yhden nurkan, painaa <code>Shift + Ctrl + (ensimmäinen suunta, josta löytyy dataa)</code> ja sitten <code>Shift + Ctrl + (toinen suunta, josta löytyy dataa)</code>. Tämä valitsee automaattisesti koko taulukon!</li>
</ul></li>
</ul>
<p><u>Voit muokata solujen sisältöä</u> klikkaamalla solua ja aloittamalla kirjoittamisen. Voit myös tuplaklikata solua, jolloin näet vilkkuvan kirjoittamiskursorin solussa.</p>
<p><u>Solun sisältöä voi myös muokata taulukkoalueen yläpuolela olevata <strong>funktioalueesta</strong></u>. Funktioalueen kätevänä osana on, että <u>voit laajentaa sitä haluamasi kokoon</u>. Vie hiiren osoitin funktioalueen alareunalle, jolloin osoitin muuttuu veto-osoittimesi. Vedä sitten funktioalue haluamasi kooksi. Excel muistaa määrittelemäsi koon jokaiselle työkirjalle erikseen. Voit pienentää funktioalueen takaisin yhdeksi riviksi, tai laajentaa se yhdestä rivistä määittelemääsi kokoon, painamalla pientä karetti-ikonia funktioalueen oikeassa päädyssä.</p>
<p><u>Funktioalueella voit myös <strong>rivittää</strong> kirjoittamasi funktiot/koodin</u>. Kun kirjoitat tekstiä funktioalueelle, pidä <code>Alt</code>-näppäintä pohjassa ja paina <code>Enter</code>, jolloin saat rivilyönnin. Excel ei välitä rivilyönneistä funktion sisällä, joten voit vapaasti rivittää funktiosi haluamaasi rivirakenteeseen. Tämä voi olla hyödyllistä jos kirjoitat paljon sisäisiä funktioita (eli funktion, joka sisältää funktion, joka sisältää…), koska niiden lukeminen voi käydä nopeasti hyvin hankalaksi.</p>
</section>
<section id="sec-viittaaminen-ja-osoitteet" class="level2 page-columns page-full" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="sec-viittaaminen-ja-osoitteet"><span class="header-section-number">13.5</span> Viittaaminen ja osoitteet</h2>
<p>Yksinkertaisimmillaan viittaaminen toiseen soluun onnistuu Excelissä samoin kuin yleisen laskennan kirjoittaminen.</p>
<div id="fig-viit-esimerkki01" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-viit-esimerkki01a" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="pics/viittaaminen/viit_esimerkki01a.png" class="img-fluid figure-img" data-ref-parent="fig-viit-esimerkki01"></p>
<figcaption class="figure-caption">(a) Arvot näkyvissä</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-viit-esimerkki01b" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="pics/viittaaminen/viit_esimerkki01b.png" class="img-fluid figure-img" data-ref-parent="fig-viit-esimerkki01"></p>
<figcaption class="figure-caption">(b) Kaavat näkyvissä</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Kuva&nbsp;13.1: Viittaaminen</figcaption><p></p>
</figure>
</div>
<div class="page-columns page-full"><p>Kuvan <a href="#fig-viit-esimerkki01b"><span>13.1 (b)</span></a> solussa B1 tehdään suora viittaus solun A1 sisältöön: <code>=A1</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Excel osaa silloin täyttää solun B1 solun A1 sisällöllä, mitä tahansa se on.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Voit asettaa kaavat näkyville tai pois näkyvistä kohdasta <code>Kaavat &gt; Näytä kaavat</code>.</p></li></div></div>
<p><u>Vittaukset voivat olla pitkäkin ketju</u> - B1 voi viitata A1:een, joka viittaa C4:ään, joka viittaa jonnekin muualle, ja niin eteenpäin. On kuitenkin suositeltavaa pitää viittausketju lyhyenä, koska sen seuraaminen voi olla hankalaa ketjun pidentyessä.</p>
<div class="page-columns page-full"><p><u>Kaksoispisteillä <code>:</code> voit viitata solualueeseen</u>. Tällöin Excel osaa hakea kaikki solut ensimmäisen ja toisen soluviittauksen välillä. Esimerkissä solussa C1 on summafunktio, jonka parametriksi on asetettu alue <code>A1:A3</code>. Excel hakee silloin kaikki arvot soluissa <code>{A1, A2, A3}</code><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, ja palauttaa ne summafunktiolle. Summafunktio laskee sitten palautetut solut yhteen, ja palauttaa lopputuloksen.</p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;Voit määritellä Excelissä arvojanan käyttäen aaltosulkeita <code>{ }</code>. Tämä on hyödyllistä, jos haluat esimerkiksi kokeilla jotain kaavaa tilapäisellä tiedolla, mutta et jostain syystä voi lisätä tietoa soluihin ja viitata niihin. Käytän aaltosulkeita tässä kirjassa sekä Excelin muodossa että matemaattisena merkintänä, mutta tulkinta on aina sama: arvot sulkujen välillä ovat yksiulotteinen matriisi, eli lista arvoja.</p></li></div></div>
<p>Esimerkkikuvassa solussa D1 on käytetty <code>JAKOJ</code>-funktiota, joka palauttaa jonkun jakolaskun jäännöksen. Sen ensimmäinen parametri on jakolaskun jaettava luku ja toinen parametri on laskun jakaja. Koska funktio viittaa soluihin <code>A3; A1</code>, Excel ajaa funktion asetuksilla <code>=JAKOJ(7; 5)</code>, jolloin tulokseksi tulee <code>2</code>.</p>
<p><u>Viittaaminen voidaan siis ymmärtää eräänlaisena osoitteiden käyttönä</u>. Jokaisella solulla on oma osoite, joka merkitään solun sarakekirjaimen ja rivinumeron avulla: solu <code>B7</code> löytyy sarakkeesta B, riviltä 7.</p>
</section>
<section id="sec-vetotoiminto" class="level2 page-columns page-full" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="sec-vetotoiminto"><span class="header-section-number">13.6</span> Vetotoiminto</h2>
<p>Jos valitset minkä tahansa solun taulukkoalueella, huomaat, että solun ympäröivän vihreän laatikon alaoikeassa nurkassa on pieni neliö. Tätä voidaan kutsua <strong>vetotoiminnoksi</strong>.</p>
<p>Vetotoiminnolla voit monistaa kyseisen solun tietoja useampaan soluun. Jos asetat luvun <code>1</code> soluun <code>A1</code>, valitset solun, pidät hiirenpainiketta pohjassa vetotoiminnon päällä ja vedät alaspäin, Excel täyttää kaikki ylivedetyt solut samalla arvolla <code>1</code>. Näet tämän samaan aikaan kun vedät pienestä tekstiruudusta hiiriosoittimen oikealla puolella.</p>
<p>Vetotoiminnon erikoisuus on kuitenkin, että se pystyy automaattisesti muuttamaan arvoja tietyn logiikan mukaan. Jos asetat luvun <code>1</code> soluun <code>A1</code> ja luvun <code>2</code> soluun <code>A2</code>, valitset molemmat solut ja lähdet vetämään alaspäin vetotoiminnosta, Excel jatkaa numerosarjaa luvuilla <code>3, 4, 5</code>, ja niin edespäin!</p>
<div class="page-columns page-full"><p><u>Tämä toimii oikeastaan millä tahansa datalla</u>, ei vain yksinkertaisella numerosarjalla tai edes vain numeroilla. Excel tulkitsee automaattisesti, millainen datasarja on kyseessä (eri numerosarjat, fyysiset katuosoitteet, kuukaudet…) ja täyttää alueen sen mukaan<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p><div class="no-row-height column-margin column-container"><li id="fn4"><p><sup>4</sup>&nbsp;Joskus tämä menee pieleen erittäin hauskasti. Excelillä oli ennen taipumusta automaattitäyttää kuukaudet tekstin mukaan: jos asetit soluihin <code>January</code> ja <code>February</code>, seuraaviksi arvoiksi Excel ehdotti <code>Maruary, Apruary</code> ja <code>Mayruary</code>. Käytä harkiten!</p></li></div></div>
<p>Vetotoiminto toimii myös viitteillä. Jos solussa <code>A1</code> on viittaus toiseen soluun, esim. <code>=B1</code>, ja vedät solun tietoja alaspäin, Excel muuttaa viittauksen aina rivin mukaan: soluun <code>A2</code> tulee <code>=B2</code>, soluun <code>A3</code> tulee <code>=B3</code>, ja niin edespäin. Sama koskee sarakkeita.</p>
<p>Jos haluat välttää vetotoiminnon viittausmuutoksia, voit käyttää <strong>lukitustoimintoa</strong>.</p>
</section>
<section id="sec-lukitustoiminto" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="sec-lukitustoiminto"><span class="header-section-number">13.7</span> Lukitustoiminto</h2>
<p><strong>Lukitustoiminto</strong> on solujen viittauksille määrätty toiminto, joka toimii operaattorilla <code>$</code>. Lukitusoperaattori kertoo Excelille, ettei sen tule siirtää viittausta jos solun tieto kopioidaan toiseen soluun tai monistetaan vetotoiminnolla.</p>
<p><u>Lukitus tehdään erikseen riveille ja sarakkeille</u>:</p>
<ul>
<li><p><code>=$A$1</code> lukitsee sekä sarakkeen että rivin. Jos tieto kopioitaisiin toiseen soluun tai monistettaisiin vetotoiminnolla, viittaus olisi aina soluun <code>A1</code>.</p></li>
<li><p><code>=$A1</code> lukitsee sarakkeen, mutta ei riviä. Jos vetäisit tämän tiedon vasemmalle, kaikki pysyisi samana (koska vain sarake muuttuu, ja sarake on tässä tilanteessa lukittu). Jos vetäisin tiedon alaspäin, rivinumerointi kuitenkin muuttuisi (koska riviä ei olla lukittu).</p></li>
<li><p><code>=A$1</code> lukitsee rivin, mutta ei saraketta. Tässä tapahtuisi päinvastaisesti kuin yllä olevassa esimerkissä: sarake voi vaihtua jos siirryt vasemmalle/oikealle, mutta rivi ei voi vaihtua jos siirryt ylöspäin/alaspäin.</p></li>
<li><p><code>=A1</code> ei lukitse mitään. Sekä rivi- että sarakeosoite muuttuu, kun kopioit tai vedät solun tiedot muualle.</p></li>
</ul>
<p><u>Lukitus on erittäin hyödyllistä tilastollisessa analyysissa</u>. Usein haluat laskea jonkun laskutoiminnon useammalle riville tai sarakkeelle, mutta osa laskutoiminnosta pysyy aina samana soluviittauksena. Voit silloin lukita ne soluviittaukset, jotka eivät tulisi muuttua, ja jättää muut auki, jolloin varmistat funktion toimivuuden kaikissa soluissa.</p>
<p><u>Muista aina tarkistaa kopioinnin/vetomonistuksen kaavion oikeellisuus!</u></p>
</section>
<section id="sec-funktiot-teoria" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="sec-funktiot-teoria"><span class="header-section-number">13.8</span> Funktiot</h2>
<p>Excelin laskennat tehdään <strong>funktioilla</strong>. Funktio on vähän kuin tehdas, joka ottaa sisään jonkun raakamateriaalin (arvon), tekee sille jotain (laskennan tai muunnoksen), ja sylkäisee ulos uuden tuotteen (uuden arvon).</p>
<p>Funktio aloitetaan aina yhtäsuuruusmerkillä <code>=</code>. Sen jälkeen tulee funktion nimi ISOILLA KIRJAIMILLA, esim. <code>SUMMA</code> tai <code>AINUTKERTAISET.ARVOT</code>. Jos funktiossa on useampi sana nimessä, ne erotellaan pisteellä <code>.</code></p>
<p>Funktion lopussa on sulut <code>()</code>. Näiden sisälle asetetaan funktion <strong>parametrit</strong>, eli määritellään, mille arvolle jotain tulisi tehdä sekä muita funktion asetuksia.</p>
<p>Kun funktio suoritetaan, voidaan sanoa että funktio <strong>kutsutaan</strong>. Kun funktio on kutsuttu, se <strong>palauttaa</strong> jonkun arvon.</p>
<p><u>Esimerkkinä voidaan ottaa summafunktio</u>:</p>
<p><code>=SUMMA(A1:A4)</code></p>
<p>Summafunktio ottaa yhden parametrin, jota voidaan kutsua <code>alue</code>-nimellä. Tämä parametri osoittaa funktiolle, mikä solualue pitäisi summata yhteen. Yllä olevassa esimerkissä tämä on määritelty alueeksi <code>A1:A4</code>, eli kaikki solut A1:n ja A4:n väliltä: <code>A1 + A2 + A3 + A3</code>.</p>
<p>Funktioihin voi syöttää joko suoran arvon tai viittauksen toiseen soluun, jossa on sopiva arvo. Jotkut funktiot, kuten summafunktio, ottavat <strong>matriisin</strong> parametrinä, jolloin määritellään useampi solu. Toiset, kuten <code>=ONVIRH()</code>, ottavat vain yhden arvon, eli yhden solun. Jotkut funktiot eivät ota mitään parametrejä, kuten funktio <code>TOSI()</code> (joka palauttaa totuusarvon <code>TOSI</code>, eli 1).</p>
</section>
<section id="sec-dynaamiset-matriisit" class="level2" data-number="13.9">
<h2 data-number="13.9" class="anchored" data-anchor-id="sec-dynaamiset-matriisit"><span class="header-section-number">13.9</span> Dynaamiset matriisit</h2>
<p>Excelin O365-versiossa uutena toimintona ovat <strong>dynaamiset matriisit</strong>. Vaikka nimi kuulostaakin hieman vaikealta, näiden käyttö on aika yksinkertaista.</p>
<p><u>Dynaaminen matriisi on tulos, jonka kaava on asetettu vain yhteen soluun, mutta joka <strong>levittyy</strong> useamman solun ylitse</u>. Esimerkkinä voidaan käyttää <code>SUODATA</code>-funktiota. Funktio ottaa data-alueen sekä jonkun ehdon, ja palauttaa kaikki solut data-alueelta joiden rivit täyttävät kyseisen ehdon. Tämä tarkoittaa, että funktio voi palauttaa erikokoisia matriiseja, riippuen ehdosta.</p>
<p>Ennen vanhaan, Excelissä piti määritellä, kuinka suurelle alueelle matriisi palautetaan. Dynaamisten matriisien myötä näin ei enää ole! Yllä kuvailtu <code>SUODATA</code>-funktio palauttaa nyt niin suuren matriisin, kuin tarvitaan.</p>
<p>Dynaamisissa matriiseissa erikoisuus on, että <u>matriisin palauttava funktio löytyy <strong>vain</strong> ensimmäisestä solusta</u> (ylävasemmasta solusta, jos kyseessä on kaksiulotteinen matriisi; ylimmästä solusta, jos kyseessä on rivimatriisi; vasemmanpuolisesta solusta, jos kyseessä on sarakematriisi).</p>
<div id="fig-viit-esimerkki02" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-viit-esimerkki02a" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="pics/viittaaminen/viit_esimerkki02a.png" class="img-fluid figure-img" data-ref-parent="fig-viit-esimerkki02"></p>
<figcaption class="figure-caption">(a) Arvot näkyvissä</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-viit-esimerkki02b" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="pics/viittaaminen/viit_esimerkki02b.png" class="img-fluid figure-img" data-ref-parent="fig-viit-esimerkki02"></p>
<figcaption class="figure-caption">(b) Kaavat näkyvissä</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Kuva&nbsp;13.2: Dynaamiset matriisit</figcaption><p></p>
</figure>
</div>
<p>Kuvassa <a href="#fig-viit-esimerkki02"><span>13.2</span></a> esiintyy kaksi saraketta, joissa on alkuperäisiä arvoja. A-sarakkeessa arvot vaihtelevat yhden ja kymmenen välillä, ja B-sarakkeessa arvot ovat joku arvoista <code>0, 1, -1</code>. Soluun D1 olen lisännyt <code>SUODATA</code>-funktion. Funktio ottaa kaikki arvot alueella <code>A1:A10</code>, ja palauttaa ne rivit, joiden vastaava arvo alueella <code>B1:B10</code> <em>ei ole</em> -1.</p>
<p>Funktio palauttaa rivimatriisin, jossa on vähemmän rivejä kuin alkuperäisissä sarakkeissa - koska minähän suodatin pois kaikki joiden B-matriisin arvo on -1. Jos kuitenkin katsoo miten kaava esiintyy (<a href="#fig-viit-esimerkki02b">Kuva&nbsp;<span>13.2 (b)</span></a>), huomaa, että kaava on kirjoitettu vain ensimmäiseen soluun, D1. Koska <code>SUODATA</code>-funktio palauttaa dynaamisen matriisin, funktio levittyy tarvitsemalle alueelleen - tämän tunnistaa kuvasta haalean sinisestä laatikosta.</p>
<p>Dynaamiset matriisit ovat erittäin tehokkaita, koska niiden avulla et tarvitse etukäteen tietää, kuinka suurelle alueelle matriisin tulisi levittäytyä.</p>
<p>Dynaamisilla matriiseilla on ominaisvirhe: <strong>#LEVITTYMINEN!</strong> Tämä voi esiintyä mm. jos levittymisalueella on jokin arvo solussa, mikä estää levittymisen. Dynaamiset matriisit toimivat vain, jos koko levittymisalue on tyhjä!</p>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopioitu!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopioitu!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./excelinkäyttöliittymä.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Excelin käyttöliittymä</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Tekijänoikeudet (c) 2023, Oliver Saal</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>