# Päivityshistoria {.unnumbered}

Tällä sivulla näet verkkokirjan päivityshistorian. Yritän pitää tämän niin ajantasalla ja tarkkana kuin voin, mutta mahdolliset pienet korjaukset voivat vahingossa mennä sivu suun.

Julkaisunumerot ovat muodossa MAJOR.MINOR. MINOR-päivitykset voivat sisältää uusia lukuja, korjauksia ynnä muita viilauksia; MAJOR-päivitykset ovat suuria muutoksia kirjaan (joita ei taida tulla usein).

Jos päivitys koskee GitHubissa annettua Issueta, tai jos jonkun käyttäjän Pull Request on mergattu kirjaan^[Pahoittelen tätä englannin käyttöä...], päivitystiedoissa löytyy linkki kyseiseen Issueen tai Pull Requestiin.

### 1.0

**Julkaisupäivämäärä**: EI VIELÄ JULKAISTU.

**Uudet luvut**:

-   T-testin teoria ja toimeenpano Excelissä.
-   Korrelaation teoria ja toimeenpano Excelissä. (EI KIRJOITETTU)
-   Ei-parametristen testien teoria ja toimeenpano Excelissä. (EI KIRJOITETTU)
-   Hypoteesitestauksen luku.
-   Luku linearisten mallien oletuksista

**Muutokset**:

-   Funktiot-luvun tiedostonimi uudelleennimetty vastaamaan luvun nimeä.
-   T-testin tiedot siirretty uuteen lukuun, korjattu ja muotoiltu.
-   T-testin LAMBDA-funktiot siirretty lukuun LAMBDA-kaavoista.
-   Lisätty README-tiedosto GitHubia varten.
-   Lisätty verkkokirjan viittausohje etusivulle.
-   Lisätty navigointitietoa etusivulle.
-   Muutettu sivupalkin oletustasoa, jotta ikkunassa olisi enemmän tyhjää tilaa.

### 0.9

**Julkaisupäivämäärä**: 22.8.2023

-   Kirjan esiversio julkaistu.

**Tunnistetut ongelmat**:

-   Jotkut luvut ovat tyhjiä.
-   Monista luvuista puuttuu lukuviittaukset.
-   Kirjoitusvirheitä...