# Aluksi {#sec-aluksi .unnumbered}

Tämä verkkokirja sisältää lisämateriaaleja Pelastusopiston kurssille **Kvantitatiiviset menetelmät**.

Kirja on jaettu osiin ja lukuihin sisällön mukaan. Sivun yläpalkista löytyy navigointi osien alla. Kun avaat jonkun luvun, kyseisen osan luvut näkyvät myös sivun oikeassa laidassa. Puhelimella saat oikean laidan valikon esille painamalla pientä valikkopainiketta sivun ylävasemmalla.

Jos siirrät hiiren jonkun luvun otsikon päälle, voit klikata pientä ketjuikonia, jolloin sivun osoitteeksi muuttuu suora linkki siihen otsikkoon. Tällä tavalla voit esimerkiksi lisätä kyseisen luvun tai alaluvun suoraan kirjanmerkkeihisi tai jakaa linkin muille. 

Mukavia tilastollisia työhetkiä!

**Kirjan versio**: {{< var version >}}

**Päivityshistoria** löytyy kirjan viimeisestä luvusta. Uusimman päivityksen tiedot löydät alla (@sec-uusin-paivitys).

## Kirjan oikeellisuus ja mahdolliset virheet {#sec-kirjan-oikeellisuus-ja-mahdolliset-virheet}

Verkkokirja on vielä kirjoitushetkellä työn alla. Siinä voi esiintyä virheitä ja muita ongelmia - vaikka toivon mukaan näin ei olisi.

Jos huomaat virheen tai haluat kommentoida kirjaa, voit tehdä sen anonyymisti [tässä kyselylomakkeessa](https://forms.gle/mVGjJKzTMVhhXoxX8). Palautelomake ei tallenna mitään henkilötietoja, eikä siihen tule lisätä muitakaan tietoturvan vuoksi.

Voit myös ehdottaa muutoksia tai raportoida ongelmia GitHubissa Issuena. Linkki löytyy jokaisen sivun oikealta puolelta, sisällysluettelon alla.

## Lähdekoodi

Verkkokirjan lähdekoodi on saatavilla [GitHubissa](https://github.com/osaal/KVANT-23-PEO). Jos haluat ehdottaa muutoksia kirjaan, voit tehdä Pull Requestin GitHubissa tai avata Issuen.

## Tekijänoikeudet {#sec-tekijänoikeudet}

Tämä verkkokirja käyttää [Creative Commons Nimeä-EiKaupallinen 4.0 Kansainvälinen](https://creativecommons.org/licenses/by-nc/4.0/deed.fi) (CC BY-NC 4.0) -lisenssiä. Voit vapaasti kopioida, levittää ja jakaa verkkokirjan sisältöä missä tahansa muodossa, sekä muokata uudelleen verkkokirjan sisältöä. Sinun on kuitenkin viitattava alkuperäiseen verkkokirjaan, nimetä lisenssi käytössäsi, sekä merkittävä kaikki muutokset, jotka olet tehnyt. Verkkokirjaa ei saa käyttää kaupallisiin tarkoituksiin.

## Viittaaminen {#sec-viittaaminen-kirja}

Voit viitata tähän kirjaan muodossa:

> Saal, O. (2023). Kvantitatiiviset menetelmät -kurssin verkkokirja. \[Versio {{< var version >}}\]. https://osaal.github.io/KVANT-23-PEO/.

## Uusin päivitys {#sec-uusin-paivitys}

{{< include historia/_1.1.qmd >}}
