# T-testi {#sec-t-testi-teoria}

**T-testi** on testiperhenimi testeille, joilla voidaan testata kvantitatiivisten muuttujien merkitsevyyttä. T-testiperheitä löytyy kaksi: **yhden otoksen t-testi** sekä **Studentin t-testi**.

**Yhden otoksen t-testillä** voidaan testata, eroaako jokin mitta (yleensä keskiarvo) merkitsevästi tietystä arvosta. Testin ei-parametrinen vastaavuus on **merkkitesti** (@sec-merkkitesti-teoria).

**Studentin t-testillä** voidaan testata kahden keskiarvon eroa tilastollisesti. Testillä tarkistetaan, onko mitattu ero tarpeeksi suuri, että voisimme luotettavasti hylätä nollahypoteesin (ettei eroa ole, eli eron koko on nolla).

Molemmat testiperheet perustuvat **t-jakaumaan**, jonka määrittelyyn käytetään jakauman vapausasteita:

```{r}
#| label: fig-t-jakauma
#| fig-cap: "T-jakauma eri vapausasteilla"
#| layout-ncol: 3
#| fig-subcap: 
#| - "df = 1"
#| - "df = 10"
#| - "df = 300"
#| echo: false
#| cache: true

for (i in c(1, 10, 300) ) {
  curve(
    dt(x, df = i),
    from = -4,
    to = 4,
    xlab = "Arvo",
    ylab = "Todennäköisyystiheys"
  )
}

```

**Mittausasteikko:** Välimatka- ja suhdeasteikko.

[Studentin T-testistä löytyy kaksi pääkategoriaa]{.underline}: parittaisen otoksen t-testi ja kahden otoksen t-testi. Näiden ero on sekä laskennallinen että teoreettinen, joten on tärkeää valita oikea testi!

**Parittaisen otoksen t-testi** testaa kahden arvon välistä eroa, kun arvot tulevat **samasta** yksiköstä (esim. vastaajasta). Tätä käytetään esimerkiksi kun samoille henkilöille tehdään mittaus ennen ja jälkeen jotain kokeellista **interventiota**, ja halutaan tarkastaa, oliko interventiolla vaikutusta. Testin ei-parametrinen vastaavuus on **Wilcoxonin signed-rank -testi** (@sec-wilcoxonin-signed-rank-testi-teoria).

**Kahden otoksen t-testi** testaa kahden eri otoksen keskiarvojen eroa, eli arvot tulevat **eri** yksiköstä (esim. eri vastaajaryhmät). Tätä voi käyttää, kun haluaa tarkastaa miten esimerkiksi kaksi sosiaalista ryhmää eroavat jollain muuttujalla. Testin ei-parametrinen vastaavuus on **Mann-Whitney'n U-testi** (@sec-mann-whitneyn-u-testi).

Tässä kirjassa kahden otoksen t-testinä käytetään **Welchin t-testiä**. Testiversio toimii muuttujilla, joiden ryhmillä on eri varianssit (eli ovat **heteroskedastisia**). Studentin T-testistä löytyy myös **homoskedastisen** suhteen t-testi, mutta koska Welchin t-testi on robustimpi, emme käytä Studentin homoskedastista t-testiä. Welchin t-testin laskeminen käsin on hankalampaa, myönnetään, mutta se on vakiintuneessa käytössä tieteessä.

## T-testin vapausasteet {#sec-t-testin-vapausasteet}

**Vapausasteet** t-testille määritellään hieman eri tavalla riippuen testimuodosta. Taulukossa [-@tbl-t-testi-vapausasteet] näkyy vapausasteiden laskentatavat:

+-----------------------------+---------------------------------------------------------+
| Testityyppi                 | Vapausasteet                                            |
+=============================+=========================================================+
| Yhden otoksen t-testi       | $\text{df} = n - 1$                                     |
+-----------------------------+---------------------------------------------------------+
| Parittaisen otoksen t-testi | $\text{df} = n - 1$                                     |
+-----------------------------+---------------------------------------------------------+
| Kahden otoksen t-testi      | $\text{df} = \frac{1}{Z_1 + Z_2}$                       |
|                             |                                                         |
|                             | $Z_k = (\frac{SD_k/n_k}{SD_1/n_1 + SD_2/ n_2})^2/(n-1)$ |
+-----------------------------+---------------------------------------------------------+

: T-testin vapausasteiden laskenta {#tbl-t-testi-vapausasteet}

Sekä yhden että parittaisen otoksen t-testin vapausasteet ovat yksinkertaisesti otoskoko miinus yksi. Kahden otoksen Welchin t-testin vapausasteet ovat hieman hankalammat. Molemmille ryhmille lasketaan $Z$-arvo: ryhmän keskihajonta jaattuna otoskoolla, ja tämä jaattuna molempien ryhmien keskihajonnan ja otoskoon jakolaskujen summalla, ja vielä tulos neliöön. Jaa sitten tulos otoskoolla miinus yksi.

## T-testin mallioletukset {#sec-t-testin-mallioletukset}

T-testillä on kolme pääsääntöistä mallioletusta: **normaalijakautuminen**, **homoskedastisiteetti** sekä **muuttujien yksikkösuhteet**.

### Normaalijakautuminen {#sec-normaalijakautuminen-t}

[T-testi olettaa, että testattava arvo tulee normaalijakaumasta]{.underline}. Tämä on kuitenkin totta suurissa otoksissa yleisesti ottaen suurten numeroiden lain ansiosta, joten siitä ei tarvitse välittää.

Jos testaat Studentin t-testillä, normaalijakautunut arvo on **testin alla oleva ero**, ei arvot itsessään.

Jos kuitenkin testaat pienellä otoskoolla, voi tällä olla vaikutusta. **Käytä mielummin ei-parametristä testiä**.

### Homoskedastisiteetti {#sec-homoskedastisiteetti-t}

[T-testi olettaa, että kahden ryhmän väliset varianssit ovat riippumattomia ryhmään kuulumisesta]{.underline} - eli että ovat samankokoisia.

Voit testata oletusta useilla eri menetelmillä (ks. @sec-mallioletukset).

Welchin t-testi on rakennettu toimimaan heteroskedastisella datajakaumalla, eli tämän rikkominen ei ole ongelma sen kannalta.

### Joko täysin samat tai täysin eri yksiköt {#sec-joko-täysin-samat-tai-täysin-eri-yksiköt-t}

[T-testi vaatii, että mittausyksiköt ovat joko täysin samat (eli otoskoko verrattavien mittojen välillä tulisi olla sama), tai täysin eri (eli ryhmä 1 ja ryhmä 2 ovat täysin eri yksiköitä).]{.underline} T-testi ei toimi, jos sinulla on sekoitus samaa ryhmää ja eri ryhmiin kuuluvia yksiköitä.

Tarkista tämä oletus miettimällä: ovatko kaikki tutkimusyksiköt samasta vai eri yksiköstä?

**Jos rikot olettamuksen, et voi käyttää t-testiä**. Tilastollisia menetelmiä tällaisen mallintamiseen löytyy (engl. *mixed models*), mutta niiden käyttö on jo huomattavasti vaikeampaa eikä onnistu luontevasti Excelissä.

### Yhteenveto vaatimuksista {#sec-yhteenveto-vaatimuksista-t}

Jos sinulla on isot otokset, ja tiedät, että molemmat muuttujat tulevat joko täysin samoista tai täysin eri yksiköistä, kaikki on hyvin ja voit jatkaa. Valitse kuitenkin oikea t-testi!

Jos sinulla on pieni otos, t-testi on herkempi normaalijakautumisen vaatimukselle. Parempi vaihtoehto voi olla **ei-parametrinen testi**. Vastaavat testit t-testille ovat **Mann-Whitney'n U-testi** (kahden otoksen testit) sekä **Wilcoxonin signed-rank-testi** (parittainen t-testi).

Jos et tiedä mitä yksikköjä on mitattu, sinun ei kannattaisi olla vielä testaamassa mitään. Tutustu dataasi enemmän ja selvitä mittaustavat!

## T-testin valitseminen {#sec-t-testin-valitseminen}

Käytä näitä kulkukaavioita oikean testin valitsemiseksi. Valitse ensin oikea välilehti, ja aloita vasemmalta puolelta.

::: panel-tabset
### Yksi muuttuja

```{mermaid}
%%| label: fig-t-yhden-kulkukaavio
%%| fig-cap: Yhden otoksen testin valitseminen
flowchart LR
  A{Otoskoko?} --> B
  A --> C
  B(Pieni) --> D
  C(Iso) ----> 1(["Yhden otoksen
  t-testi"])
  D{Normaalijakauma?} --> E
  D --> F
  E(Kyllä) --> 1
  F(Ei) --> 2([Merkkitesti])

```

### Kaksi muuttujaa (samat yksiköt)

```{mermaid}
%%| label: fig-t-kahden-sama-kulkukaavio
%%| fig-cap: Kahden muuttujan testin valitseminen, kun yksiköt ovat samoja
flowchart LR
  A{Otoskoko?} --> B
  A --> C
  B(Pieni) --> D
  C(Iso) ----> 1(["Parittaisen otok-
  sen t-testi"])
  D{Normaalijakauma?} --> E
  D --> F
  E(Kyllä) --> 1
  F(Ei) --> 2(["Wilcoxon
  signed-rank"])
```

### Kaksi muuttujaa (eri yksiköt)

```{mermaid}
%%| label: fig-t-kahden-eri-kulkukaavio
%%| fig-cap: Kahden muuttujan testin valitseminen, kun yksiköt ovat eri
flowchart LR
  A{Otoskoko?} --> B
  A --> C
  B(Pieni) --> D
  C(Iso) ----> G
  D{Normaalijakauma?} --> E
  D --> F
  E(Kyllä) --> G
  F(Ei) --> 2([Mann-Whitney U])
  G([Welchin t-testi])
```
:::

## T-testin laskeminen {#sec-t-testin-laskeminen}

[T-testin laskukaavat eroavat testiperheiden välillä]{.underline}. Varmista siis aina ensin, onko kyseessä yhden otoksen tesi, parittaisen otoksen testi vai kahden otoksen testi.

### Yhden otoksen t-testi {#sec-yhden-otoksen-t-testi-teoria}

Yhden otoksen t-testin kaava on:

$$
t = \frac{\bar{x} - \mu}{s/\sqrt{n}}
$$ {#eq-t-1}

$\bar{x}$ on keskiarvo, jota halutaan testata. $\mu$ on koko, jota vastaan testataan. Jos testataan vain, eroaako keskiarvo nollasta, tämän voi jättää pois kokonaan.

$s$ on jakauman keskihajonta, ja $n$ on otoskoko.

### Parittaisen otoksen t-testi {#sec-parittaisen-otoksen-t-testi-teoria}

Parittaisen otoksen t-testin kaava on:

$$ t = \frac{1/n\sum{x-y}} {\sigma/\sqrt{n}} $$ {#eq-t-2}

$1/n\sum{x-y}$ on erotuksen keskiarvo[^ttesti-1], $\sigma$ on erotuksen keskihajonta, ja $\sqrt{n}$ on otoskoon neliöjuuri.

[^ttesti-1]: Jonkun asian jakaminen n:llä on sama kuin sen kertominen 1/n:llä. Tämä osuus on vain yleinen keskiarvolaskelma, vaikka kirjoitettuna hieman eri muotoon, eli $\frac{\sum{x-y}}{n}$.

Laske ensin muuttujien väliset erotukset uudeksi muuttujaksi. Laske sitten tämän muuttujan keskiarvo ja keskihajonta. Syötä viimeiseksi nämä, sekä otoskoon neliöjuuri, kaavaan. Lopputulos on parittaisen t-testin testisuure.

### Kahden otoksen (Welchin) t-testi {#sec-kahden-otoksen-welchin-t-testi-teoria}

**Kahden otoksen Welchin t-testin** kaava on:

$$
t = \frac{\bar{x} - \bar{y}} {S'_D}
$$

$\bar{x} - \bar{y}$ on ryhmien keskiarvojen ero. $S'_D$ on **ryhmitetyn varianssin keskivirhe**, joka itsessään koostuu monesta osasta:

$$
S'_D = S_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}
$$

Ryhmitetyn varianssin keskivirhe on itse ryhmitetty varianssi $S_p$ kertaa otoskokojen inverssien summan neliöjuuri $\sqrt{1/n_1 + 1/n_2}$.

**Ryhmitetty varianssi** (engl. *pooled variance*) ottaa huomioon molempien ryhmien eri keskihajonnat ja otoskoot:

$$
S_p = \sqrt{\frac{(n_1 - 1) s^2_1 + (n_2 - 1) s^2_2}{n_1 + n_2 - 2}}
$$

Kaavan laskenta kannattaa aloittaa "alhaalta ylös". Ensin lasketaan ryhmien keskihajonnat (muista keskihajontojen nostaminen neliöön!), sitten ryhmitetty varianssi. Sitten kerrotaan ryhmitetty varianssi otoskokojen inverssien summan neliöjuurella saadaksemme ryhmitetyn varianssin keskivirhe. Viimeiseksi lasketaan keskiarvojen erotus ja jaataan tulos ryhmitetyn varianssin keskivirheellä. Lopputulos on Welchin t-testin suure.

## Mittakoon laskeminen {#sec-mittakoon-laskeminen-t}

T-testille voidaan laskea mittakoko, joko Pearsonin $r$ tai Cohenin $\hat{d}$. Suosittavaa on kuitenkin, että raportoit ensisijaisesti itse testatut arvot ja/tai eron (esimerkiksi prosenttiero), mutta näiden mittakokojen avulla muut tutkijat voivat hyödyntää tuloksiasi helpommin meta-analyyseissa.

Voit laskea **Pearsonin** $r$**-suureen** kaavalla:

$$
r = \sqrt{\frac{t^2}{t^2+\text{df}}}
$$ {#eq-t-5}

jossa $t^2$ on t-testin tulos neliöön, ja $df$ on testin vapausasteet.

Voit myös laskea **Cohenin** $\hat{d}$**-suureen** kaavalla:

$$
\hat{d} = \frac{\bar{x}-\bar{y}}{s_{\bar{y}}}
$$ {#eq-t-6}

jossa $\bar{x}$ ja $\bar{y}$ ovat mitatut keskiarvot ja $s_{\bar{y}}$ on toisen keskiarvon keskihajonta.

Parittaisen t-testin $\hat{d}$-suureelle löytyy myös korjattu versio, joka ottaa huomioon parittaisten mittausten yhteiskorrelaation:

$$
\hat{d}_D = \frac{\hat{d}}{\sqrt{1-r}}
$$ {#eq-t-7}

jossa $r$ on yllä oleva $r$-suure.

## T-testin laskeminen Excelissä {#sec-t-testin-laskeminen-excelissä}

Excelissä löytyy valmis kaava, jolla saat **Studentin t-testin** p-arvon:

-   `T.TESTI(matriisi1; matriisi2; suunta; laji)`

    -   Syötä kaavalle molemmat datamatriisit

    -   `Suunta`-parametriin määrittelet, käytätkö yksisuuntaista `1` vai kaksisuuntaista `2` häntää

    -   `Laji`-parametrilla määrittelet, teetkö parittaisen `1`, kahden otoksen homoskedastisen `2` vai kahden otoksen heteroskedastisen `3` t-testin

Funktio: @sec-t-testi

[**Yhden otoksen t-testin** laskeminen:]{.underline}

1.  Hae testattava muuttuja uuteen sarakkeeseen, suodattaen tyhjät solut pois: `=SUODATA(testattava_muuttuja; testattava_muuttuja <> "")`
    1.  Käytä tätä aluetta seuraavissa laskuissa parametreissä `muuttuja`
2.  Laske t-suure: `=(KESKIARVO(muuttuja) - testattava_arvo) / (KESKIHAJONTA.S(muuttuja) / NELIÖJUURI(LASKE(muuttuja)))`
    1.  Jos testattava arvo on `0`, voit jättää sen kokonaan pois kaavasta.
3.  Laske t-suureen vapausasteet: `= LASKE(muuttuja) - 1`
4.  Hae t-suuren todennäköisyys:
    1.  Yksisuuntainen:
        1.  Vasenhäntäinen: `=T.JAKAUMA(ITSEISARVO(t-suure); vapausasteet; EPÄTOSI)`
        2.  Oikeahäntäinen: `=T.JAKAUMA.OH(ITSEISARVO(t-suure); vapausasteet)`
    2.  Kaksisuuntainen: `=T.JAKAUMA.2S(ITSEISARVO(t-suure); vapausasteet)`
5.  Laske t-suureen luottamusväli:
    1.  Suuri otos:
        1.  Yläraja: `=KESKIARVO(muuttuja) + LUOTTAMUSVÄLI.NORM(alfa / 2; KESKIHAJONTA.S(muuttuja); LASKE(muuttuja))`
        2.  Alaraja: `=KESKIARVO(muuttuja) - LUOTTAMUSVÄLI.NORM(alfa / 2; KESKIHAJONTA.S(muuttuja); LASKE(muuttuja))`
    2.  Pieni otos:
        1.  Yläraja: `=KESKIARVO(muuttuja) + LUOTTAMUSVÄLI.T(alfa / 2; KESKIHAJONTA.S(muuttuja); LASKE(muuttuja))`
        2.  Alaraja: `=KESKIARVO(muuttuja) - LUOTTAMUSVÄLI.T(alfa / 2; KESKIHAJONTA.S(muuttuja); LASKE(muuttuja))`
    3.  Parametri `alfa` edustaa valitsemaasi alfatasoa, esim. `0,05` (95 % luottamusvälille).
6.  Laske mittakoko:
    1.  Pearsonin $r$: `=NELIÖJUURI(t-suure ^ 2 / (t-suure ^ 2 + vapausasteet))`
    2.  Cohenin $\hat{d}$: `=KESKIARVO(muuttuja) - testattava_arvo / VAR.S(muuttuja)`
    3.  Cohenin korjattu $d$: `=cohenin_d / NELIÖJUURI(1 - r)`

[**Parittaisen t-testin** laskeminen:]{.underline}

1.  Hae testattavat muuttujat uusiin sarakkeisiin, suodattaen tyhjät arvot parillisesti pois:
    1.  Muuttuja 1: `=SUODATA(muuttuja1_alkuperäinen; (muuttuja1_alkuperäinen <> "") * (muuttuja2_alkuperäinen <> ""))`
    2.  Muuttuja 2: `=SUODATA(muuttuja2_alkuperäinen; (muuttuja1_alkuperäinen <> "") * (muuttuja2_alkuperäinen <> ""))`
    3.  Käytä näitä alueita seuraavissa laskuissa parametreissä `muuttuja1` ja `muuttuja2`
2.  Laske muuttujien erotus uudeksi muuttujaksi: `=muuttuja1# - muuttuja2#`
3.  Laske erotuksen keskiarvo ja keskihajonta: `=KESKIARVO(erotus)` ja `=KESKIHAJONTA.S(erotus)`
4.  Laske parittainen t-suure: `=KESKIARVO(erotus) / (KESKIHAJONTA.S(erotus) / NELIÖJUURI(LASKE(erotus)))`
5.  Laske t-suureen vapausasteet: `=LASKE(erotus) - 1`
6.  Hae t-suureen todennäköisyys:
    1.  Yksisuuntainen:
        1.  Vasenhäntäinen: `=T.JAKAUMA(ITSEISARVO(t-suure); vapausasteet; EPÄTOSI)`
        2.  Oikeahäntäinen: `=T.JAKAUMA.OH(ITSEISARVO(t-suure); vapausasteet)`
    2.  Kaksisuuntainen: `=T.JAKAUMA.2S(ITSEISARVO(t-suure); vapausasteet)`
7.  Laske t-suureen luottamusväli:
    1.  Suuri otos:
        1.  Yläraja: `=KESKIARVO(erotus) + LUOTTAMUSVÄLI.NORM(alfa / 2; KESKIHAJONTA.S(erotus); LASKE(erotus))`
        2.  Alaraja: `=KESKIARVO(erotus) - LUOTTAMUSVÄLI.NORM(alfa / 2; KESKIHAJONTA.S(erotus); LASKE(erotus))`
    2.  Pieni otos:
        1.  Yläraja: `=KESKIARVO(erotus) + LUOTTAMUSVÄLI.T(alfa / 2; KESKIHAJONTA.S(erotus); LASKE(erotus))`
        2.  Alaraja: `=KESKIARVO(erotus) - LUOTTAMUSVÄLI.T(alfa / 2; KESKIHAJONTA.S(erotus); LASKE(erotus))`
    3.  Parametri `alfa` edustaa valitsemaasi alfatasoa, esim. `0,05` (95 % luottamusvälille).
8.  Laske mittakoko:
    1.  Pearsonin $r$: ``` =``NELIÖJUURI(t-suure ^ 2 / (t-suure ^ 2 + vapausasteet)) ```
    2.  Cohenin $\hat{d}$: `=erotus / NELIÖJUURI(VAR.S(erotus))`

[**Kahden otoksen t-testin** laskeminen:]{.underline}

1.  Hae riippuvaisen muuttujan data uusiin sarakkeisiin ryhmityksen mukaan, suodattaen tyhjät pois:
    1.  Ryhmä 1: `=SUODATA(riippuvainen_muuttuja; (ryhmämuuttuja = ryhmä1nro) * (riippuvainen_muuttuja <> ""))`
    2.  Ryhmä 2: `=SUODATA(riippuvainen_muuttuja; (ryhmämuuttuja = ryhmä2nro) * (riippuvainen_muuttuja <> ""))`
    3.  Käytä näitä alueita seuraavissa muuttujissa parametreissä `ryhmä1` ja `ryhmä2`
2.  Laske ryhmien keskiarvot: `=KESKIARVO(ryhmä1)` ja `=KESKIARVO(ryhmä2)`
3.  Laske ryhmien keskihajonnat: `=KESKIHAJONTA.S(ryhmä1)` ja `=KESKIHAJONTA.S(ryhmä2)`
4.  Laske ryhmien varianssit: `=VAR.S(ryhmä1)` ja `=VAR.S(ryhmä2)`
5.  Laske ryhmäkoot: `=LASKE(ryhmä1)` ja `=LASKE(ryhmä2)`
6.  Laske ryhmille z-koot:
    1.  Ryhmä 1: `=((varianssi1/koko1) / (varianssi1/koko1 + varianssi2/koko2))^2 / (koko1 - 1)`
    2.  Ryhmä 2: `=((varianssi2/koko2) / (varianssi1/koko1 + varianssi2/koko2))^2 / (koko2 - 1)`
7.  Laske keskiarvojen erotus: `=keskiarvo1 - keskiarvo2`
8.  Laske ryhmitetty varianssi: `=((koko1 - 1) * keskihajonta1 ^ 2 + (koko2 - 1) * keskihajonta2 ^ 2) / (koko1 + koko2 - 2)`
9.  Laske ryhmitetyn varianssin keskivirhe: `=NELIÖJUURI(ryhmitetty_varianssi) * NELIÖJUURI(1 / koko1 + 1 / koko2)`
10. Laske t-suure: `=keskiarvojen_erotus / ryhmitetyn_varianssin_keskivirhe`
11. Laske t-suureen vapausasteet: `=1 / (z_1 + z_2)`
12. Hae t-suureen todennäköisyys:
    1.  Yksisuuntainen:
        1.  Vasenhäntäinen: `=T.JAKAUMA(ITSEISARVO(t-suure); vapausasteet; EPÄTOSI)`
        2.  Oikeahäntäinen: `=T.JAKAUMA.OH(ITSEISARVO(t-suure); vapausasteet)`
    2.  Kaksisuuntainen: `=T.JAKAUMA.2S(ITSEISARVO(t-suure); vapausasteet)`
13. Laske t-suureen luottamusväli:
    1.  Suuri otos:
        1.  Yläraja: `=keskiarvojen_erotus + LUOTTAMUSVÄLI.NORM(alfa / 2; 1; MAKS(koko1; koko2)) * ryhmitetty_varianssin_keskivirhe`
        2.  Alaraja: `=keskiarvojen_erotus - LUOTTAMUSVÄLI.NORM(alfa / 2; 1; MAKS(koko1; koko2)) * ryhmitetty_varianssin_keskivirhe`
    2.  Pieni otos:
        1.  Yläraja: `=keskiarvojen_erotus + LUOTTAMUSVÄLI.T(alfa / 2; 1; MAKS(koko1; koko2)) * ryhmitetty_varianssin_keskivirhe`
        2.  Alaraja: `=keskiarvojen_erotus - LUOTTAMUSVÄLI.T(alfa / 2; 1; MAKS(koko1; koko2)) *ryhmitetty_varianssin_keskivirhe`
    3.  Parametri `alfa` edustaa valitsemaasi alfatasoa, esim. `0,05` (95 % luottamusvälille).
14. Laske mittakoko:
    1.  Pearsonin $r$: `=NELIÖJUURI(t-suure ^ 2 / (t-suure ^ 2 + vapausasteet))`
    2.  Cohenin $\hat{d}$: `=keskiarvojen_erotus / NELIÖJUURI(ryhmitetty_varianssi)`

## T-testin raportointi {#sec-t-testin-raportointi}

T-testille tulisi mieluisesti raportoida seuraavat tiedot:

-   Testin tyyppi (yhden, parittaisen vai kahden otoksen testi)

-   Verratut arvot $\bar{x}$ ja $\bar{y}$

-   Testisuure $t$

-   Vapausasteet $\text{df}$

-   P-arvo $p$ (ja/tai luottamusväli $\text{CI}$)

-   Mittakoko (Pearsonin $r$ tai Cohenin $\hat{d}$)

-   (Jos tehty) Levenen testin tai varianssivertailun tulokset (Levenen testille testisuure ja $p$, varianssivertailulle varianssit ja niiden ero tai graafinen esittely).

::: callout-note
## Esimerkki t-testin raportoinnista

Yleisen vaaramerkin toimintamallien osaamisessa on sukupuolittuneita eroja. Naisista 10 prosenttia osaavat toimia oikein, mutta miehistä vain 5 prosenttia. Ero on tilastollisesti merkitsevä (t = 4,942, df = 2830,6, *p* \< 0,0001, eron 95% CI \[0,03; 0,07\]). Cohenin *d*-suure osoittaa keskikokoista eroa (d = 0,135, 95% CI \[0,064; 0,206\]). Testissä käytettiin kahden otoksen Welchin t-suuretta, koska Levenen testi oli merkitsevä (Levenen testi = 100,2, *p* \< 0,0001).
:::
